/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Ventas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.Modelos.Caja;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.CajaDaoImpl;
import net.dao.LoginDaoImpl;
import net.dao.UsuarioDaoImpl;
import net.util.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Searp
 */
public class CajaApp extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public CajaApp(java.awt.Frame parent, boolean modal) throws UnknownHostException {
         super(parent, modal);
        initComponents();
        arranque()  ;
        setLocationRelativeTo(null);
    }

    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final CajaDaoImpl cdao = new CajaDaoImpl(st);
    private DefaultTableModel modelpr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_Presupuesto = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapres = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        agregarpres = new javax.swing.JButton();
        cancelarpres = new javax.swing.JButton();
        fechapres = new javax.swing.JFormattedTextField();
        buscarpres = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        txthoraini = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtfechaini = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        botapertura = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtimporteini = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtfechacie = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txthoracie = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtimportecie = new javax.swing.JTextField();
        botcierre = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtcheque = new javax.swing.JTextField();
        txttarjetas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtefectivo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt100 = new javax.swing.JTextField();
        txt50 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt05 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();

        Buscar_Presupuesto.setSize(new java.awt.Dimension(650, 750));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Buscar Factura");

        tablapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablapres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane3.setViewportView(tablapres);

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarpres.setText("Agregar");
        agregarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarpresMouseEntered(evt);
            }
        });
        agregarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpresActionPerformed(evt);
            }
        });

        cancelarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarpres.setText("Cancelar");
        cancelarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpresMouseClicked(evt);
            }
        });
        cancelarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpresActionPerformed(evt);
            }
        });

        try {
            fechapres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechapres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarpres.setText("Buscar Fecha");
        buscarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechapres, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarpres, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechapres, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PresupuestoLayout = new javax.swing.GroupLayout(Buscar_Presupuesto.getContentPane());
        Buscar_Presupuesto.getContentPane().setLayout(Buscar_PresupuestoLayout);
        Buscar_PresupuestoLayout.setHorizontalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_PresupuestoLayout.setVerticalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de Caja");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtusuario);
        txtusuario.setBounds(410, 10, 153, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtnro);
        txtnro.setBounds(62, 10, 90, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(botbuscar);
        botbuscar.setBounds(160, 10, 157, 30);

        txthoraini.setEditable(false);
        txthoraini.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txthoraini.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthoraini.setText("  :   ");
        jPanel2.add(txthoraini);
        txthoraini.setBounds(210, 70, 100, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setText("Hora");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(170, 70, 40, 30);

        txtfechaini.setEditable(false);
        try {
            txtfechaini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfechaini.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechaini.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtfechaini);
        txtfechaini.setBounds(60, 70, 90, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel13.setText("Fecha");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 70, 40, 30);

        botapertura.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botapertura.setText("Apertura");
        botapertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaperturaActionPerformed(evt);
            }
        });
        botapertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaperturaKeyPressed(evt);
            }
        });
        jPanel2.add(botapertura);
        botapertura.setBounds(580, 70, 80, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel14.setText("Importe inicial");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(330, 70, 80, 30);

        txtimporteini.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtimporteini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimporteiniActionPerformed(evt);
            }
        });
        jPanel2.add(txtimporteini);
        txtimporteini.setBounds(410, 70, 150, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "CIERRE"));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Fecha");

        txtfechacie.setEditable(false);
        try {
            txtfechacie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfechacie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechacie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Hora");

        txthoracie.setEditable(false);
        txthoracie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txthoracie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthoracie.setText("  :   ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Importe de Cierre");

        txtimportecie.setEditable(false);
        txtimportecie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        botcierre.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botcierre.setText("Cierre");
        botcierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcierreActionPerformed(evt);
            }
        });
        botcierre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botcierreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtfechacie, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txthoracie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtimportecie, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botcierre, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfechacie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthoracie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtimportecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botcierre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ARQUEO"));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setText("Monto Cheques");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 30, 80, 30);

        txtcheque.setEditable(false);
        txtcheque.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtcheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchequeActionPerformed(evt);
            }
        });
        jPanel4.add(txtcheque);
        txtcheque.setBounds(90, 30, 110, 30);

        txttarjetas.setEditable(false);
        txttarjetas.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txttarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarjetasActionPerformed(evt);
            }
        });
        jPanel4.add(txttarjetas);
        txttarjetas.setBounds(320, 30, 110, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("Monto Tarjetas");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(240, 30, 80, 30);

        txtefectivo.setEditable(false);
        txtefectivo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtefectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtefectivoActionPerformed(evt);
            }
        });
        jPanel4.add(txtefectivo);
        txtefectivo.setBounds(550, 30, 110, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel16.setText("Monto Efectivo");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(470, 30, 80, 30);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalles de Arqueo"));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel17.setText("100.000");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel18.setText("5.000");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel19.setText("10.000");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel20.setText("50.000");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel21.setText("20.000");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel22.setText("2.000");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel27.setText("1.000");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel28.setText("500");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt05, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt100)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt05, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt20, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total Caja"));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel26.setText("Total Recaudacion");

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botaperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaperturaActionPerformed
        try {
            apertura();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(CajaApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaperturaActionPerformed

    private void txtimporteiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimporteiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteiniActionPerformed

    private void botcierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcierreActionPerformed
        cierre();// TODO add your handling code here:
    }//GEN-LAST:event_botcierreActionPerformed

    private void txtchequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchequeActionPerformed

    private void txttarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarjetasActionPerformed

    private void txtefectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtefectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtefectivoActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void botaperturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaperturaKeyPressed
        try {
            apertura();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(CajaApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaperturaKeyPressed

    private void botcierreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botcierreKeyPressed
        cierre();
// TODO add your handling code here:
    }//GEN-LAST:event_botcierreKeyPressed

    private void agregarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseClicked

    }//GEN-LAST:event_agregarpresMouseClicked

    private void agregarpresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarpresMouseEntered

    private void agregarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpresActionPerformed
        retornarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpresActionPerformed

    private void cancelarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresMouseClicked

    private void cancelarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpresActionPerformed
        Buscar_Presupuesto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresActionPerformed

    private void buscarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpresActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajaApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CajaApp dialog = null;
                try {
                    dialog = new CajaApp(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CajaApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Presupuesto;
    private javax.swing.JButton agregarpres;
    private javax.swing.JButton botapertura;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botcierre;
    private javax.swing.JButton buscarpres;
    private javax.swing.JButton cancelarpres;
    private javax.swing.JFormattedTextField fechapres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablapres;
    private javax.swing.JTextField txt05;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txtcheque;
    private javax.swing.JTextField txtefectivo;
    private javax.swing.JFormattedTextField txtfechacie;
    private javax.swing.JFormattedTextField txtfechaini;
    private javax.swing.JTextField txthoracie;
    private javax.swing.JTextField txthoraini;
    private javax.swing.JTextField txtimportecie;
    private javax.swing.JTextField txtimporteini;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txttarjetas;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    
    private Calendar f;
    Caja caj = null;
    private void arranque() throws UnknownHostException{
    //campos
    List<Caja> list = cdao.list();
    for (Caja l : list){
        if(l.getEstado().equals("ACTIVO")){
            caj = l;
        }
    }
    if(caj != null){
            botapertura.setEnabled(false);
            txtnro.setEnabled(false);
            txtusuario.setText(caj.getUsuario().getNombre());
            txtnro.setText(String.valueOf(caj.getId_caja()));
            f = (Calendar.getInstance());
            txtfechaini.setText(retornarString(caj.getFechaini()));
            txthoraini.setText(rentornarStringhora(caj.getFechaini()));
            txtimporteini.setText(String.valueOf(caj.getMontoini()));
            txtimporteini.setEnabled(false);
            txtcheque.setText(String.valueOf(caj.getCheque()));
            txttarjetas.setText(String.valueOf(caj.getTarjeta()));
            txtefectivo.setText(String.valueOf(caj.getEfectivo()));
            txt100.setText(null);
            txt50.setText(null);
            txt20.setText(null);
            txt10.setText(null);
            txt5.setText(null);
            txt1.setText(null);
            txt2.setText(null);
            txt05.setText(null);

            
            txttotal.setText(null);

            txtfechacie.setText(null);
            txthoracie.setText(null);
            txtimportecie.setText(null);
            
            Total();

            botcierre.setEnabled(true);
    }else{
            
            txtnro.setEnabled(false);
            txtnro.setText(null);
            f = (Calendar.getInstance());
            txtfechaini.setText(retornarString(f));
            txthoraini.setText(rentornarStringhora(f));
            txtimporteini.setText(null);
            txtcheque.setText(null);
            txttarjetas.setText(null);
            txtefectivo.setText(null);
            txt100.setText(null);
            txt50.setText(null);
            txt20.setText(null);
            txt10.setText(null);
            txt5.setText(null);
            txt1.setText(null);
            txt2.setText(null);
            txt05.setText(null);
            Total();
            retornarusuario();
            txtfechacie.setText(null);
            txthoracie.setText(null);
            txtimportecie.setText(null);

            botcierre.setEnabled(false);
        }
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private String rentornarStringhora (Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("HH:mm");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void apertura() throws UnknownHostException{
        if(!txtimporteini.getText().isEmpty()){
                        Usuario us = udao.buscarPorNom(txtusuario.getText());
                        Caja l = new Caja(f,Integer.parseInt(txtimporteini.getText()),0,0,0,"ACTIVO",us);
                        cdao.guardar(l);
                        JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
                        arranque();
        }else{
            JOptionPane.showMessageDialog(null, "Informe el monto de apertura");
        }
    }
    
    private void Total(){
        
        if(caj == null){
            txttotal.setText(null);
        }else{
            int tot = caj.getCheque() + caj.getTarjeta() + caj.getEfectivo();
            txttotal.setText(String.valueOf(tot));
        }
    }
    
    
    
    private void cierre(){
        if(!txt100.getText().isEmpty() && !txt50.getText().isEmpty() && !txt20.getText().isEmpty() && !txt10.getText().isEmpty() && !txt5.getText().isEmpty()
        && !txt2.getText().isEmpty() && !txt1.getText().isEmpty() && !txt05.getText().isEmpty()){
                
                    Caja l = cdao.buscarPorId(Integer.parseInt(txtnro.getText()));
                    l.setD100(Integer.parseInt(txt100.getText()));
                    l.setD50(Integer.parseInt(txt50.getText()));
                    l.setD20(Integer.parseInt(txt20.getText()));
                    l.setD10(Integer.parseInt(txt10.getText()));
                    l.setD5(Integer.parseInt(txt5.getText()));
                    l.setD2(Integer.parseInt(txt2.getText()));
                    l.setD1(Integer.parseInt(txt1.getText()));
                    l.setD05(Integer.parseInt(txt05.getText()));
                    l.setMontocie(Integer.parseInt(txttotal.getText()));
                    l.setEstado("CERRADO");
                    
                    l.setFechacie(f);
                    cdao.actualizar(l);
                    
                    txt100.setEnabled(false);
                    txt50.setEnabled(false);
                    txt20.setEnabled(false);
                    txt10.setEnabled(false);
                    txt5.setEnabled(false);
                    txt1.setEnabled(false);
                    txt2.setEnabled(false);
                    txt05.setEnabled(false);
                    
                    botcierre.setEnabled(false);
               
           
        }else{
            JOptionPane.showMessageDialog(null, "Informe correctamente el arqueo de caja");
        }
    }
    
    private void tablaPresupuesto(){
        tablapres.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablapres.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpr = (DefaultTableModel)tablapres.getModel();
        modelpr.setNumRows(0);
        List<Caja> list = cdao.list();
        for (Caja l : list){
            if (l.getEstado().equals("CERRADO")) {
                
                if(fechapres.getText().equals("  /  /    ")){
                   modelpr.addRow(new Object[]{
                    l.getId_caja(),retornarString(l.getFechacie())
                }); 
                }else{
                   if(fechapres.getText().equals(retornarString(l.getFechacie()))){
                       modelpr.addRow(new Object[]{
                    l.getId_caja(),retornarString(l.getFechacie())
                }); 
                   }
                }
            }
        }
    }
    
    private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Presupuesto.setModal(true);
        Buscar_Presupuesto.setLocation(x,y);
        Buscar_Presupuesto.setLocationRelativeTo(null);
        Buscar_Presupuesto.setVisible(true);
    }
     
    private void retornarPresupuesto(){
        if(tablapres.getRowCount() > 0){
            if(tablapres.getSelectedRow() != -1){
            Caja pe = cdao.buscarPorId(Integer.parseInt(modelpr.getValueAt(tablapres.getSelectedRow(), 0).toString()));
            txtnro.setText(String.valueOf(pe.getId_caja()));
            txtfechaini.setText(retornarString(pe.getFechaini()));
            txtfechacie.setText(retornarString(pe.getFechaini()));
            txtusuario.setText(String.valueOf(pe.getUsuario().getNombre()));
            txthoraini.setText(rentornarStringhora(pe.getFechaini()));
            txthoracie.setText(rentornarStringhora(pe.getFechacie()));
            txtimporteini.setText(String.valueOf(pe.getMontoini()));
            txtcheque.setText(String.valueOf(pe.getCheque()));
            txttarjetas.setText(String.valueOf(pe.getTarjeta()));
            txtefectivo.setText(String.valueOf(pe.getEfectivo()));
            txt100.setText(String.valueOf(pe.getD100()));
            txt50.setText(String.valueOf(pe.getD50()));
            txt20.setText(String.valueOf(pe.getD20()));
            txt10.setText(String.valueOf(pe.getD10()));
            txt5.setText(String.valueOf(pe.getD5()));
            txt2.setText(String.valueOf(pe.getD2()));
            txt1.setText(String.valueOf(pe.getD1()));
            txt05.setText(String.valueOf(pe.getD05()));
            txttotal.setText(String.valueOf(pe.getMontocie()));
            txtimportecie.setText(String.valueOf(pe.getMontocie()));
            Buscar_Presupuesto.dispose();
            
                    txt100.setEnabled(false);
                    txt50.setEnabled(false);
                    txt20.setEnabled(false);
                    txt10.setEnabled(false);
                    txt5.setEnabled(false);
                    txt1.setEnabled(false);
                    txt2.setEnabled(false);
                    txt05.setEnabled(false);
                    
                    botcierre.setEnabled(false);
                    
            }
        }
    }
    
    
}
