/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Compras;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.Modelos.Ajuste_stock;
import net.Modelos.Det_ajuste_stock;
import net.Modelos.Producto;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.Ajuste_stock_daoimpl;
import net.dao.Det_ajuste_stock_daoimpl;
import net.dao.LoginDaoImpl;
import net.dao.Producto_daoimpl;
import net.dao.UsuarioDaoImpl;
import net.util.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Ramc
 */
public class Ajuste_Stock_app extends javax.swing.JDialog {

    /**
     * Creates new form Presupuesto
     */
    public Ajuste_Stock_app(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque()  ;
        setLocationRelativeTo(null);
    }
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final Producto_daoimpl pdao = new Producto_daoimpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private DefaultTableModel modelpr, modelpe, model;
    private final Ajuste_stock_daoimpl pedao = new Ajuste_stock_daoimpl(st);
    //private final Det_ajuste_stock_daoimpl  = new Det_ajuste_stock_daoimpl(st);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_producto = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaprod = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        filtroprod = new javax.swing.JTextField();
        agregarprod = new javax.swing.JButton();
        cancelarprod = new javax.swing.JButton();
        Buscar_Pedido = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botimprimir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtnroproducto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        botbuscarproducto = new javax.swing.JButton();
        botagregar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtobservaciones = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        botnuevo = new javax.swing.JButton();
        botguardar = new javax.swing.JButton();
        botsalir = new javax.swing.JButton();
        botcancelar = new javax.swing.JButton();
        botquitar = new javax.swing.JButton();
        botanular = new javax.swing.JButton();
        txtestado = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();

        Buscar_producto.setResizable(false);
        Buscar_producto.setSize(new java.awt.Dimension(650, 750));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Buscar Producto");

        tablaprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ));
        jScrollPane2.setViewportView(tablaprod);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filtroprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        filtroprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtroprodKeyTyped(evt);
            }
        });

        agregarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarprod.setText("Agregar");
        agregarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarprodMouseClicked(evt);
            }
        });
        agregarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarprodActionPerformed(evt);
            }
        });

        cancelarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarprod.setText("Cancelar");
        cancelarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarprodMouseClicked(evt);
            }
        });
        cancelarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroprod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(agregarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarprod, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarprod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroprod))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_productoLayout = new javax.swing.GroupLayout(Buscar_producto.getContentPane());
        Buscar_producto.getContentPane().setLayout(Buscar_productoLayout);
        Buscar_productoLayout.setHorizontalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        Buscar_productoLayout.setVerticalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Pedido.setSize(new java.awt.Dimension(650, 750));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Buscar Ajuste");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane3.setViewportView(tablaped);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpedActionPerformed(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PedidoLayout = new javax.swing.GroupLayout(Buscar_Pedido.getContentPane());
        Buscar_Pedido.getContentPane().setLayout(Buscar_PedidoLayout);
        Buscar_PedidoLayout.setHorizontalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_PedidoLayout.setVerticalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Registro de Ajuste de Stock");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtfecha);
        txtfecha.setBounds(610, 10, 99, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 10, 58, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario);
        txtusuario.setBounds(800, 10, 153, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro de Ajuste");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 135, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtnro);
        txtnro.setBounds(150, 10, 112, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar Ajuste");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botbuscar);
        botbuscar.setBounds(280, 10, 157, 30);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO", "DESCRIPCION", "OBSERVACION"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        botimprimir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botimprimir.setText("Imprimir");
        botimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botimprimirActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel19.setText("Nro");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(20, 30, 40, 30);

        txtnroproducto.setEditable(false);
        txtnroproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(txtnroproducto);
        txtnroproducto.setBounds(70, 30, 50, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel20.setText("Descripcion");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(130, 30, 90, 30);

        txtdescripcion.setEditable(false);
        txtdescripcion.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(txtdescripcion);
        txtdescripcion.setBounds(210, 30, 370, 30);

        botbuscarproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarproducto.setText("Buscar Producto");
        botbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarproductoActionPerformed(evt);
            }
        });
        jPanel7.add(botbuscarproducto);
        botbuscarproducto.setBounds(600, 30, 130, 30);

        botagregar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botagregar.setText("Agregar Producto");
        botagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botagregarActionPerformed(evt);
            }
        });
        jPanel7.add(botagregar);
        botagregar.setBounds(750, 30, 130, 30);

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel22.setText("Nro");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(20, 30, 40, 30);

        jTextField19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel8.add(jTextField19);
        jTextField19.setBounds(70, 30, 50, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel23.setText("Descripcion");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(130, 30, 90, 30);

        jTextField20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel8.add(jTextField20);
        jTextField20.setBounds(210, 30, 370, 30);

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton18.setText("Buscar Producto");
        jPanel8.add(jButton18);
        jButton18.setBounds(600, 30, 130, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel24.setText("Precio");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(740, 30, 80, 30);

        jTextField21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel8.add(jTextField21);
        jTextField21.setBounds(790, 30, 120, 30);

        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton19.setText("Agregar Producto");
        jPanel8.add(jButton19);
        jButton19.setBounds(930, 30, 130, 30);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel1.setText("Observaciones");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(20, 90, 90, 30);

        txtobservaciones.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(txtobservaciones);
        txtobservaciones.setBounds(110, 90, 600, 30);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botnuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botnuevo.setText("Nuevo");
        botnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnuevoActionPerformed(evt);
            }
        });

        botguardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botguardar.setText("Guardar");
        botguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botguardarActionPerformed(evt);
            }
        });

        botsalir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botsalir.setText("Salir");
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });

        botcancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botcancelar.setText("Cancelar");
        botcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcancelarActionPerformed(evt);
            }
        });

        botquitar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botquitar.setText("Quitar");
        botquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botquitarActionPerformed(evt);
            }
        });

        botanular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botanular.setText("Anular");
        botanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botanularActionPerformed(evt);
            }
        });

        txtestado.setBackground(new java.awt.Color(102, 102, 102));
        txtestado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(482, 482, 482)
                .addComponent(botquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(421, 421, 421)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botquitar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botcancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botsalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel25.setText("Tipo de Ajuste");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(20, 30, 120, 30);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel10.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel26.setText("Nro");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(20, 30, 40, 30);

        jTextField22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel10.add(jTextField22);
        jTextField22.setBounds(70, 30, 50, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel27.setText("Descripcion");
        jPanel10.add(jLabel27);
        jLabel27.setBounds(130, 30, 90, 30);

        jTextField23.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel10.add(jTextField23);
        jTextField23.setBounds(210, 30, 370, 30);

        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton20.setText("Buscar Producto");
        jPanel10.add(jButton20);
        jButton20.setBounds(600, 30, 130, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel28.setText("Precio");
        jPanel10.add(jLabel28);
        jLabel28.setBounds(740, 30, 80, 30);

        jTextField24.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel10.add(jTextField24);
        jTextField24.setBounds(790, 30, 120, 30);

        jButton21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton21.setText("Agregar Producto");
        jPanel10.add(jButton21);
        jButton21.setBounds(930, 30, 130, 30);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 0, 0, 0);

        combo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aumento", "Descuento" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel9.add(combo);
        combo.setBounds(150, 30, 140, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(968, Short.MAX_VALUE)
                .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(407, 407, 407)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botimprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botimprimirActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void filtroprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroprodKeyTyped
        filtroprod.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (filtroprod.getText());//.toUpperCase();
                filtroprod.setText(cadena);
                repaint();
                filtroPr();
            }
        });
        trsfiltro = new TableRowSorter(tablaprod.getModel());
        tablaprod.setRowSorter(trsfiltro);// TODO add your handling code here:
    }//GEN-LAST:event_filtroprodKeyTyped

    private void agregarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarprodMouseClicked

    }//GEN-LAST:event_agregarprodMouseClicked

    private void agregarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarprodActionPerformed
        agregarProductos();// TODO add your handling code here:
    }//GEN-LAST:event_agregarprodActionPerformed

    private void cancelarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarprodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarprodMouseClicked

    private void cancelarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarprodActionPerformed
        Buscar_producto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarprodActionPerformed

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked
        retornarFactura();
    }//GEN-LAST:event_agregarpedMouseClicked

    private void cancelarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpedActionPerformed
        Buscar_Pedido.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedActionPerformed

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarfactura();  // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarproductoActionPerformed
        buscarproductos();        // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarproductoActionPerformed

    private void botagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botagregarActionPerformed
        agregar();        // TODO add your handling code here:
    }//GEN-LAST:event_botagregarActionPerformed

    private void botnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnuevoActionPerformed
        try {
            nuevo();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Ajuste_Stock_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botnuevoActionPerformed

    private void botguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botguardarActionPerformed
        try {
            guardar();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Ajuste_Stock_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botguardarActionPerformed

    private void botanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botanularActionPerformed
        anular();// TODO add your handling code here:
    }//GEN-LAST:event_botanularActionPerformed

    private void botquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botquitarActionPerformed
        removerProducto();// TODO add your handling code here:
    }//GEN-LAST:event_botquitarActionPerformed

    private void botcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcancelarActionPerformed
        try {
            arranque();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Ajuste_Stock_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botcancelarActionPerformed

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_botsalirActionPerformed

    private void tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseEntered

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        selecTable();// TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orden_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orden_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orden_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orden_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ajuste_Stock_app dialog = null;
                try {
                    dialog = new Ajuste_Stock_app(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Ajuste_Stock_app.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Pedido;
    private javax.swing.JDialog Buscar_producto;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarprod;
    private javax.swing.JButton botagregar;
    private javax.swing.JButton botanular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botbuscarproducto;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton botguardar;
    private javax.swing.JButton botimprimir;
    private javax.swing.JButton botnuevo;
    private javax.swing.JButton botquitar;
    private javax.swing.JButton botsalir;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarprod;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JTextField filtroprod;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablaprod;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txtestado;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnroproducto;
    private javax.swing.JTextField txtobservaciones;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    private Calendar f;
    private void arranque() throws UnknownHostException{
        txtnro.setText(null);
        combo.setEnabled(true);
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        txtnroproducto.setText(null);
        txtdescripcion.setText(null);
        txtobservaciones.setText(null);
        txtobservaciones.setEnabled(false);
        botbuscarproducto.setEnabled(false);
        botagregar.setEnabled(false);
        botquitar.setEnabled(false);
        botguardar.setEnabled(false);
        
        botanular.setEnabled(false);
        txtestado.setText(null);
        tabla.setEnabled(true);
        botnuevo.setEnabled(true);
        tableModel();
        retornarusuario();
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private void tableModel(){
    tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabla.getColumnModel().getColumn(1).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(2).setPreferredWidth(130);
    model = (DefaultTableModel)tabla.getModel();
    model.setNumRows(0);
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void nuevo() throws UnknownHostException{
        retornarusuario();
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        botbuscarproducto.setEnabled(true);
        botnuevo.setEnabled(false);
        botguardar.setEnabled(true);
    }
    
    private TableRowSorter trsfiltro;
    public void filtroPr() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtroprod.getText(), 1));
    }
    
    private void tabproductos(){
        tablaprod.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaprod.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpr = (DefaultTableModel)tablaprod.getModel();
        modelpr.setNumRows(0);
        List<Producto> list = pdao.list();
        for (Producto l : list){
            
            modelpr.addRow(new Object[]{
                l.getId_prod(), l.getDescripcion()
            });
          
        }
    }
    
    private void buscarproductos(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabproductos();
        Buscar_producto.setModal(true);
        Buscar_producto.setLocation(x,y);
        Buscar_producto.setLocationRelativeTo(null);
        Buscar_producto.setVisible(true);
    }
    
    private void agregarProductos(){
        if(tablaprod.getRowCount() > 0){
            if(tablaprod.getSelectedRow() != -1){
                Producto l = pdao.buscarPorId(Integer.parseInt(modelpr.getValueAt(tablaprod.getSelectedRow(), 0).toString()));
                txtnroproducto.setText(String.valueOf(l.getId_prod()));
                txtdescripcion.setText(l.getDescripcion());
                botagregar.setEnabled(true);
                txtobservaciones.setEnabled(true);
                Buscar_producto.dispose();
            }
        }
    }
    
    private void tabpedidos(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpe = (DefaultTableModel)tablaped.getModel();
        modelpe.setNumRows(0);
        List<Ajuste_stock> list = pedao.list();
        for (Ajuste_stock l : list){
            modelpe.addRow(new Object[]{
                l.getId_aj(), retornarString(l.getFecha())
            });
        }
    }
     
     private void buscarfactura(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabpedidos();
        Buscar_Pedido.setModal(true);
        Buscar_Pedido.setLocation(x,y);
        Buscar_Pedido.setLocationRelativeTo(null);
        Buscar_Pedido.setVisible(true);
    }
     
     private void retornarFactura(){
          if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
                Ajuste_stock pe = pedao.buscarPorId(Integer.parseInt(modelpe.getValueAt(tablaped.getSelectedRow(), 0).toString()));
                txtfecha.setText(retornarString(pe.getFecha()));
                txtusuario.setText(String.valueOf(pe.getId_us().getNombre()));
                txtnro.setText(String.valueOf(pe.getId_aj()));
                List<Det_ajuste_stock> dt =pe.getDetalles();
                model.setNumRows(0);
                tabla.setEnabled(false);
                for (Det_ajuste_stock p : dt) {
                    model.addRow(new Object[]{
                        p.getCantidad(),p.getId_pro().getId_prod(),p.getId_pro().getDescripcion(), p.getObservacion()
                    });
                } 
                txtestado.setText(pe.getEstado());
                if(txtestado.getText().equals("ACTIVO")){
                    botanular.setEnabled(true);
                }else{
                    botanular.setEnabled(false);
                }
                Buscar_Pedido.dispose();
            }
          }
    }
     
    private void limpiar(){
        txtnroproducto.setText(null);
        txtdescripcion.setText(null);
        txtobservaciones.setText(null);
        txtobservaciones.setEnabled(false);
        botbuscarproducto.setEnabled(true);
        botagregar.setEnabled(false);
        botquitar.setEnabled(true);
        indice=0;
    }
    
    private int indice;
    
    private int productoAgregado(int n){
        int b = 0;
            if(tabla.getRowCount() > 0){
                for (int i = 0; i < tabla.getRowCount(); i++) {
                    if(Integer.parseInt(model.getValueAt(i, 1).toString()) != n){
                        b = 0;
                    }else{
                        b = n;
                        indice = i;
                        break;
                    }
                }
            }
        return b;
    }
    
    private boolean esNum(String n){
        boolean b;
        try{
            int x = Integer.parseInt(n);
            b=true;
        }catch (Exception e){
            b=false;
        }
        return b;
    }
    
    private String can;
    private void agregar(){
        Producto se = pdao.buscarPorId(Integer.parseInt(txtnroproducto.getText()));
        int sto = se.getStock();
        if(!txtobservaciones.getText().isEmpty()){
            can = JOptionPane.showInputDialog("Ingrese Cantidad");
            
            if(esNum(can)){
                if(combo.getSelectedItem().toString().equals("Descuento")  && Integer.parseInt(can) > sto){
                    JOptionPane.showMessageDialog(null, "Cantidad de ajuste supera al stock actual");
                }else{
                    if(productoAgregado(Integer.parseInt(txtnroproducto.getText())) == 0){

                            model.addRow(new Object[]{
                            can,txtnroproducto.getText(),txtdescripcion.getText(),txtobservaciones.getText()
                            });
                            limpiar();
                            combo.setEnabled(false);


                    }else{
                        if(JOptionPane.showConfirmDialog(null, "Desea sumar la cantidad.", "Producto ya agredado", JOptionPane.YES_OPTION) == 0){
                           int x = Integer.parseInt(can) + Integer.parseInt(model.getValueAt(indice, 0 ).toString());
                           model.setValueAt(x, indice, 0);
                           limpiar();

                        }
                    }
                        
                }
                    
            }else{
                JOptionPane.showMessageDialog(null, "Cantidad debe ser un numero");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese Observaciones");
        }
    }
    
    private void removerProducto(){
        if(tabla.getRowCount() > 0){
            if(tabla.getSelectedRow() != -1){
                model.removeRow(tabla.getSelectedRow());
            }
        }
    }
    
    private void guardar() throws UnknownHostException{
        if(tabla.getRowCount() > 0){
            if(!txtusuario.getText().isEmpty() && combo.getSelectedIndex()>-1){
                if(JOptionPane.showConfirmDialog(null, "Desea guardar este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
                    Usuario us = udao.buscarPorNom(txtusuario.getText());
                    Ajuste_stock aj = new Ajuste_stock(f,"ACTIVO", combo.getSelectedItem().toString(), us);
                    for (int i = 0; i < tabla.getRowCount(); i++) {
                        Det_ajuste_stock dt= new Det_ajuste_stock();
                        dt.setCantidad(Integer.parseInt(model.getValueAt(i, 0).toString()));
                        dt.setObservacion(model.getValueAt(i, 3).toString());
                        Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        dt.setId_pro(p);
                        aj.getDetalles().add(dt);
                        dt.setId_aj(aj);
                        
                        int stk = p.getStock();
                        if(combo.getSelectedItem().toString().equals("Aumento")){
                            p.setStock(stk + Integer.parseInt(model.getValueAt(i, 0).toString()));
                        }else{
                            p.setStock(stk - Integer.parseInt(model.getValueAt(i, 0).toString()));
                        }
                        pdao.actualizar(p);
                                    
                    }
                    pedao.guardar(aj);
                    JOptionPane.showMessageDialog(null, "Guardado correctamente");
                    arranque();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Campo vacio");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue un libro al carro de compras");
        }
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Ajuste_stock pre = pedao.buscarPorId(Integer.parseInt(txtnro.getText()));
                if(pre.getEstado().equals("ACTIVO")){
                    pre.setEstado("ANULADO");
                    botanular.setEnabled(false);
                    pedao.actualizar(pre);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular, El registro esta siendo utilizado en otra instancia");
                }
            }
        }
    }
    
    private void selecTable(){
        if(tabla.getRowCount()> 0){
            if(tabla.isEnabled()){
                if(tabla.getSelectedRow()> -1){
                   Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(tabla.getSelectedRow(),1).toString()));
                   txtnroproducto.setText(String.valueOf(p.getId_prod()));
                   txtdescripcion.setText(p.getDescripcion());
                   txtobservaciones.setText(model.getValueAt(tabla.getSelectedRow(),3).toString());
                   botquitar.setEnabled(true);
                }
            }
        }
    }
    
    
    
}
