/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Compras;

import Reportes.fac_comreport;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.Modelos.Det_factura_com;
import net.Modelos.Det_nota_credito;
import net.Modelos.Factura_com;
import net.Modelos.Libroiva;
import net.Modelos.Nota_credito;
import net.Modelos.Producto;
import net.Modelos.Proveedor;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.Det_nota_credito_daoimpl;
import net.dao.Factura_com_daoimpl;
import net.dao.LibroivaDaoImpl;
import net.dao.LoginDaoImpl;
import net.dao.Nota_credito_daoimpl;
import net.dao.Producto_daoimpl;
import net.dao.ProveedorDaoImpl;
import net.dao.UsuarioDaoImpl;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.util.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Ramc
 */
public class Nota_creditoapp extends javax.swing.JDialog {

    /**
     * Creates new form Presupuesto
     */
    public Nota_creditoapp(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque();
        setLocationRelativeTo(null);
    }
    
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final Producto_daoimpl pdao = new Producto_daoimpl(st);
    private final ProveedorDaoImpl cdao = new ProveedorDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final LibroivaDaoImpl lidao = new LibroivaDaoImpl(st);
    private final Factura_com_daoimpl ordao = new Factura_com_daoimpl(st);
    private final Nota_credito_daoimpl ncdao = new Nota_credito_daoimpl(st);
    private final Det_nota_credito_daoimpl dtdao = new Det_nota_credito_daoimpl(st);
    private DefaultTableModel modelpr,modelclie, modelpres, model, modelpe;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_Pedido = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        Buscar_Presupuesto = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapres = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        agregarpres = new javax.swing.JButton();
        cancelarpres = new javax.swing.JButton();
        fechapres = new javax.swing.JFormattedTextField();
        buscarpres = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtnroproducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        botagregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botnuevo = new javax.swing.JButton();
        botguardar = new javax.swing.JButton();
        botsalir = new javax.swing.JButton();
        botcancelar = new javax.swing.JButton();
        botquitar = new javax.swing.JButton();
        botanular = new javax.swing.JButton();
        txtestado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        txtnroproveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        botimprimir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txttotal10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttotal5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtpedido = new javax.swing.JTextField();
        botbuscarpedido = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        txttimbradofac = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        combotipo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtfechafac = new javax.swing.JFormattedTextField();
        txttimbrado = new javax.swing.JTextField();

        Buscar_Pedido.setSize(new java.awt.Dimension(650, 750));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Buscar Orden de Compra");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane5.setViewportView(tablaped);

        jPanel10.setBackground(new java.awt.Color(153, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });
        agregarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpedActionPerformed(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpedActionPerformed(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PedidoLayout = new javax.swing.GroupLayout(Buscar_Pedido.getContentPane());
        Buscar_Pedido.getContentPane().setLayout(Buscar_PedidoLayout);
        Buscar_PedidoLayout.setHorizontalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        Buscar_PedidoLayout.setVerticalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Presupuesto.setSize(new java.awt.Dimension(650, 750));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Buscar Nota de Credito");

        tablapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablapres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "PROVEEDOR"
            }
        ));
        jScrollPane3.setViewportView(tablapres);

        jPanel11.setBackground(new java.awt.Color(153, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarpres.setText("Agregar");
        agregarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarpresMouseEntered(evt);
            }
        });
        agregarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpresActionPerformed(evt);
            }
        });

        cancelarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarpres.setText("Cancelar");
        cancelarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpresMouseClicked(evt);
            }
        });
        cancelarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpresActionPerformed(evt);
            }
        });

        try {
            fechapres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechapres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarpres.setText("Buscar Fecha");
        buscarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechapres, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarpres, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechapres, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PresupuestoLayout = new javax.swing.GroupLayout(Buscar_Presupuesto.getContentPane());
        Buscar_Presupuesto.getContentPane().setLayout(Buscar_PresupuestoLayout);
        Buscar_PresupuestoLayout.setHorizontalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );
        Buscar_PresupuestoLayout.setVerticalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Registro de Nota de Credito");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtfecha);
        txtfecha.setBounds(610, 10, 99, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 10, 58, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtusuario);
        txtusuario.setBounds(800, 10, 153, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro de Nota de Credito");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 135, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtnro);
        txtnro.setBounds(150, 10, 112, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar Nota de Credito");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botbuscar);
        botbuscar.setBounds(280, 10, 157, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Nro");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 30, 40, 30);

        txtnroproducto.setEditable(false);
        txtnroproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtnroproducto);
        txtnroproducto.setBounds(70, 30, 50, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Descripcion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(130, 30, 90, 30);

        txtdescripcion.setEditable(false);
        txtdescripcion.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtdescripcion);
        txtdescripcion.setBounds(210, 30, 270, 30);

        botagregar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botagregar.setText("Agregar Producto");
        botagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botagregarActionPerformed(evt);
            }
        });
        jPanel3.add(botagregar);
        botagregar.setBounds(500, 30, 130, 30);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botnuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botnuevo.setText("Nuevo");
        botnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnuevoActionPerformed(evt);
            }
        });

        botguardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botguardar.setText("Guardar");
        botguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botguardarActionPerformed(evt);
            }
        });

        botsalir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botsalir.setText("Salir");
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });

        botcancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botcancelar.setText("Cancelar");
        botcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcancelarActionPerformed(evt);
            }
        });

        botquitar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botquitar.setText("Quitar");
        botquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botquitarActionPerformed(evt);
            }
        });

        botanular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botanular.setText("Anular");
        botanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botanularActionPerformed(evt);
            }
        });

        txtestado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(493, 493, 493)
                .addComponent(botquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(421, 421, 421)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botquitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("Nro");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 20, 50, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("RUC");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(140, 20, 50, 30);

        txtruc.setEditable(false);
        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });
        jPanel2.add(txtruc);
        txtruc.setBounds(170, 20, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Razon Social");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 20, 80, 30);

        txtrazonsocial.setEditable(false);
        txtrazonsocial.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtrazonsocial);
        txtrazonsocial.setBounds(420, 20, 220, 30);

        txtnroproveedor.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtnroproveedor);
        txtnroproveedor.setBounds(80, 20, 50, 30);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1090, -120, 52, 900);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO", "DESCRIPCION", "PRECIO", "TOTAL"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("TOTAL");

        txttotal.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        botimprimir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botimprimir.setText("Imprimir");
        botimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botimprimirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel16.setText("IVA 10%");

        txttotal10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel17.setText("IVA 5%");

        txttotal5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Factura de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel18.setText("Nro");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(20, 30, 40, 30);

        txtpedido.setEditable(false);
        txtpedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel6.add(txtpedido);
        txtpedido.setBounds(70, 30, 110, 30);

        botbuscarpedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarpedido.setText("Buscar Factura de Compra");
        botbuscarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarpedidoActionPerformed(evt);
            }
        });
        jPanel6.add(botbuscarpedido);
        botbuscarpedido.setBounds(200, 30, 180, 30);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel19.setText("Nro");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(20, 30, 40, 30);

        jTextField16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(jTextField16);
        jTextField16.setBounds(70, 30, 50, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel20.setText("Descripcion");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(130, 30, 90, 30);

        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(jTextField17);
        jTextField17.setBounds(210, 30, 370, 30);

        jButton15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton15.setText("Buscar Producto");
        jPanel7.add(jButton15);
        jButton15.setBounds(600, 30, 130, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel21.setText("Precio");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(740, 30, 80, 30);

        jTextField18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel7.add(jTextField18);
        jTextField18.setBounds(790, 30, 120, 30);

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton16.setText("Agregar Producto");
        jPanel7.add(jButton16);
        jButton16.setBounds(930, 30, 130, 30);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, 0, 0, 0);

        txttimbradofac.setEditable(false);
        txttimbradofac.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel6.add(txttimbradofac);
        txttimbradofac.setBounds(430, 30, 153, 30);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel22.setText("Condicion de pago");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(20, 30, 120, 30);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel23.setText("Nro");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(20, 30, 40, 30);

        jTextField20.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel9.add(jTextField20);
        jTextField20.setBounds(70, 30, 50, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel24.setText("Descripcion");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(130, 30, 90, 30);

        jTextField21.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel9.add(jTextField21);
        jTextField21.setBounds(210, 30, 370, 30);

        jButton18.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton18.setText("Buscar Producto");
        jPanel9.add(jButton18);
        jButton18.setBounds(600, 30, 130, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel25.setText("Precio");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(740, 30, 80, 30);

        jTextField22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel9.add(jTextField22);
        jTextField22.setBounds(790, 30, 120, 30);

        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton19.setText("Agregar Producto");
        jPanel9.add(jButton19);
        jButton19.setBounds(930, 30, 130, 30);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(0, 0, 0, 0);

        combotipo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        combotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoActionPerformed(evt);
            }
        });
        jPanel8.add(combotipo);
        combotipo.setBounds(150, 30, 140, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel26.setText("Timbrado");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(20, 90, 80, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setText("Fecha de Factura");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(20, 140, 90, 30);

        try {
            txtfechafac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfechafac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechafac.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel8.add(txtfechafac);
        txtfechafac.setBounds(140, 140, 99, 30);

        txttimbrado.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel8.add(txttimbrado);
        txttimbrado.setBounds(150, 90, 153, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    private void botimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botimprimirActionPerformed
        try {
            imprimir();// TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(Nota_creditoapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botimprimirActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void combotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipoActionPerformed

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked

    }//GEN-LAST:event_agregarpedMouseClicked

    private void agregarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpedActionPerformed
        retornarFactura();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpedActionPerformed

    private void cancelarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpedActionPerformed
        Buscar_Pedido.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedActionPerformed

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tabpedidos();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    private void agregarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseClicked

    }//GEN-LAST:event_agregarpresMouseClicked

    private void agregarpresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarpresMouseEntered

    private void agregarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpresActionPerformed
        retornarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpresActionPerformed

    private void cancelarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresMouseClicked

    private void cancelarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpresActionPerformed
        Buscar_Presupuesto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresActionPerformed

    private void buscarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpresActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpresActionPerformed

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
         buscarPresupuesto();       // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botbuscarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarpedidoActionPerformed
        buscarfactura();        // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarpedidoActionPerformed

    private void botnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnuevoActionPerformed
        try {
            nuevo();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Nota_creditoapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botnuevoActionPerformed

    private void botguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botguardarActionPerformed
        try {
            guardar();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Nota_creditoapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botguardarActionPerformed

    private void botanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botanularActionPerformed
        anular();        // TODO add your handling code here:
    }//GEN-LAST:event_botanularActionPerformed

    private void botquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botquitarActionPerformed
        removerProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_botquitarActionPerformed

    private void botcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcancelarActionPerformed
        try {
            arranque();        // TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Nota_creditoapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botcancelarActionPerformed

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_botsalirActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        selecTable();        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void botagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botagregarActionPerformed
        agregar();        // TODO add your handling code here:
    }//GEN-LAST:event_botagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nota_creditoapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nota_creditoapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nota_creditoapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nota_creditoapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Nota_creditoapp dialog = null;
                try {
                    dialog = new Nota_creditoapp(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Nota_creditoapp.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Pedido;
    private javax.swing.JDialog Buscar_Presupuesto;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarpres;
    private javax.swing.JButton botagregar;
    private javax.swing.JButton botanular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botbuscarpedido;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton botguardar;
    private javax.swing.JButton botimprimir;
    private javax.swing.JButton botnuevo;
    private javax.swing.JButton botquitar;
    private javax.swing.JButton botsalir;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton buscarpres;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarpres;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JFormattedTextField fechapres;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablapres;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txtestado;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JFormattedTextField txtfechafac;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnroproducto;
    private javax.swing.JTextField txtnroproveedor;
    private javax.swing.JTextField txtpedido;
    private javax.swing.JTextField txtrazonsocial;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttimbrado;
    private javax.swing.JTextField txttimbradofac;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotal10;
    private javax.swing.JTextField txttotal5;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
    private Calendar f;
    private void arranque() throws UnknownHostException{
        txtnro.setText(null);
        txtestado.setText(null);
        txttimbrado.setEnabled(false);
        txtfechafac.setEnabled(false);
        txttotal.setText(null);
        txttotal10.setText(null);
        txttotal5.setText(null);
        combotipo.setEnabled(false);
        combotipo.setSelectedIndex(-1);
        txttimbrado.setText(null);
        txtfechafac.setText(null);
        txtnro.setEnabled(false);
        txtnroproducto.setText(null);
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        txtnroproveedor.setText(null);
        txtruc.setText(null);
        txtrazonsocial.setText(null);
        txtdescripcion.setText(null);
        botbuscar.setEnabled(true);
        botbuscarpedido.setEnabled(false);
        botquitar.setEnabled(false);
        botguardar.setEnabled(false);
        txtpedido.setText(null);
        botanular.setEnabled(false);
        tabla.setEnabled(true);
        botnuevo.setEnabled(true);
        tableModel();
        retornarusuario();
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void tableModel(){
    tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabla.getColumnModel().getColumn(1).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(2).setPreferredWidth(130);
    tabla.getColumnModel().getColumn(3).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(4).setPreferredWidth(130);
    model = (DefaultTableModel)tabla.getModel();
    model.setNumRows(0);
    }
    
    private void nuevo() throws UnknownHostException{
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        retornarusuario();
        tabla.setEnabled(true);
        txttimbrado.setEnabled(true);
        txtfechafac.setEnabled(true);
        botbuscar.setEnabled(false);
        botnuevo.setEnabled(false);
        botbuscarpedido.setEnabled(true); 
        botguardar.setEnabled(true);
    }
    
    private void tabpedidos(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpe = (DefaultTableModel)tablaped.getModel();
        modelpe.setNumRows(0);
        List<Factura_com> list = ordao.list();
        for (Factura_com l : list){
            if(l.getEstado().equals("ACTIVO")){
               if(fechaped.getText().equals("  /  /    ")){
                    modelpe.addRow(new Object[]{
                    l.getId_fac(), retornarString(l.getFecha())
                    }); 
               }else{
                   if(fechaped.getText().equals(retornarString(l.getFecha()))){
                        modelpe.addRow(new Object[]{
                        l.getId_fac(), retornarString(l.getFecha())
                        }); 
                   }
               }
            }  
        }
    }
    
    private void buscarfactura(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabpedidos();
        Buscar_Pedido.setModal(true);
        Buscar_Pedido.setLocation(x,y);
        Buscar_Pedido.setLocationRelativeTo(null);
        Buscar_Pedido.setVisible(true);
    }
    
    private void retornarFactura(){
        if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
            Factura_com or = ordao.buscarPorId(Integer.parseInt(modelpe.getValueAt(tablaped.getSelectedRow(), 0).toString()));
            txtpedido.setText(String.valueOf(or.getId_fac()));
            combotipo.setSelectedItem(or.getTipo());
            txttimbradofac.setText(or.getTimbrado());
            txtnroproveedor.setText(String.valueOf(or.getId_prov().getId_prov()));
            txtruc.setText(String.valueOf(or.getId_prov().getRuc()));
            txtrazonsocial.setText(String.valueOf(or.getId_prov().getRazon_social()));
            List<Det_factura_com> dt =or.getDetalles();
            model.setNumRows(0);
            tabla.setEnabled(true);
            for (Det_factura_com p : dt) {
                model.addRow(new Object[]{
                    p.getCantidad(),  p.getId_prod().getId_prod(),  p.getId_prod().getDescripcion(),  p.getPrecio(),  (p.getCantidad() * p.getPrecio())
                });
            } 
            botnuevo.setEnabled(false);
            Buscar_Pedido.dispose();
            botbuscar.setEnabled(false);
             total();
            }
        }
    }
    
    private void tablaPresupuesto(){
        tablapres.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablapres.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablapres.getColumnModel().getColumn(2).setPreferredWidth(180);
        modelpres = (DefaultTableModel)tablapres.getModel();
        modelpres.setNumRows(0);
        List<Nota_credito> list = ncdao.list();
        for (Nota_credito l : list){
            
                if(fechapres.getText().equals("  /  /    ")){
                   modelpres.addRow(new Object[]{
                    l.getId_nc(),retornarString(l.getFecha()),l.getId_prov().getRazon_social()
                }); 
                }else{
                   if(fechapres.getText().equals(retornarString(l.getFecha()))){
                       modelpres.addRow(new Object[]{
                    l.getId_nc(), retornarString(l.getFecha()),l.getId_prov().getRazon_social()
                }); 
                   }
                }
            
        }
    }
     
     private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Presupuesto.setModal(true);
        Buscar_Presupuesto.setLocation(x,y);
        Buscar_Presupuesto.setLocationRelativeTo(null);
        Buscar_Presupuesto.setVisible(true);
    }
     
    private void retornarPresupuesto(){
        if(tablapres.getRowCount() > 0){
            if(tablapres.getSelectedRow() != -1){
            Nota_credito pe = ncdao.buscarPorId(Integer.parseInt(modelpres.getValueAt(tablapres.getSelectedRow(), 0).toString()));
            txtnro.setText(String.valueOf(pe.getId_nc()));
            txtfecha.setText(retornarString(pe.getFecha()));
            txtusuario.setText(String.valueOf(pe.getId_us().getNombre()));
            txtpedido.setText(String.valueOf(pe.getId_fac().getId_fac()));
            txttimbradofac.setText(pe.getId_fac().getTimbrado());
            txtnroproveedor.setText(String.valueOf(pe.getId_prov().getId_prov()));
            txtruc.setText(String.valueOf(pe.getId_prov().getRuc()));
            txtrazonsocial.setText(String.valueOf(pe.getId_prov().getRazon_social()));
            combotipo.setSelectedItem(pe.getTipo());
            txttimbrado.setText(pe.getTimbrado());
            txtfechafac.setText(pe.getFecha_fac());
            List<Det_nota_credito> dt =pe.getDetalles();
            model.setNumRows(0);
            tabla.setEnabled(false);
            for (Det_nota_credito p : dt) {
                model.addRow(new Object[]{
                    p.getCantidad(),p.getId_prod().getId_prod(),p.getId_prod().getDescripcion(),p.getPrecio(),(p.getCantidad() * p.getPrecio())
                });
            } 
            botnuevo.setEnabled(false);
            Buscar_Presupuesto.dispose();
            botbuscar.setEnabled(false);
            txtestado.setText(pe.getEstado());

            if(pe.getEstado().equals("ACTIVO")){
                botanular.setEnabled(true);
            }else{
                botanular.setEnabled(false);
            }
             total();
            }
        }
    }
    
    
    private void total(){
        txttotal.setText(null);
        txttotal10.setText(null);
        txttotal5.setText(null);
        int tot=0;
        int tot10=0;
        int tot5=0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            Producto pro = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
            if(pro.getIva().equals("10%")){
                tot10 = tot10 + (Integer.parseInt(model.getValueAt(i, 4).toString()));
            }else{
                if(pro.getIva().equals("5%")){
                    tot5 = tot5 + (Integer.parseInt(model.getValueAt(i, 4).toString()));
                }
            }
            tot= tot + (Integer.parseInt(model.getValueAt(i, 4).toString()));
            
        }
        tot10 = tot10 / 11;
        tot5 = tot5 /  11;
        txttotal.setText(String.valueOf(tot));
        txttotal10.setText(String.valueOf(tot10));
        txttotal5.setText(String.valueOf(tot5));
    }
    
    private void removerProducto(){
        if(tabla.getRowCount() > 0){
            if(tabla.getSelectedRow() != -1){
                model.removeRow(tabla.getSelectedRow());
            }
        }
        total();
        limpiar();
        botagregar.setEnabled(true);
    }
    private void limpiar(){
        txtnroproducto.setText(null);
        txtdescripcion.setText(null);
        botagregar.setEnabled(false);
        botquitar.setEnabled(true);
        indice=0;
        botquitar.setEnabled(false);
    }
    
    private int indice;
    
    private int productoAgregado(int n){
        int b = 0;
            if(tabla.getRowCount() > 0){
                for (int i = 0; i < tabla.getRowCount(); i++) {
                    if(Integer.parseInt(model.getValueAt(i, 1).toString()) != n){
                        b = 0;
                    }else{
                        b = n;
                        indice = i;
                        break;
                    }
                }
            }
        return b;
    }
    
    private boolean esNum(String n){
        boolean b;
        try{
            int x = Integer.parseInt(n);
            b=true;
        }catch (Exception e){
            b=false;
        }
        return b;
    }
    
    private String can;
    private void agregar(){
        if(txtnroproducto.getText().isEmpty()){
            can = JOptionPane.showInputDialog("Ingrese monto de descuento");
            if(esNum(can)){
                if(productoAgregado(1) == 0){
                    model.addRow(new Object[]{
                    1,1,"Descuento",can,can
                    });
                    limpiar();
                    total();

                }else{
                    JOptionPane.showMessageDialog(null, "ya se ha agregado un descuento");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Monto debe ser un numero");
            }
        }else{
            can = JOptionPane.showInputDialog("Ingrese Cantidad");
            if(esNum(can)){
                if(productoAgregado(Integer.parseInt(txtnroproducto.getText())) == 0){
                    model.addRow(new Object[]{
                    can,txtnro.getText(),txtdescripcion.getText()
                    });
                    limpiar();
                    total();
                }else{
                    if(JOptionPane.showConfirmDialog(null, "desear reemplazar la cantidad.", "Producto ya agredado", JOptionPane.YES_OPTION) == 0){
                       int x = Integer.parseInt(can);
                       model.setValueAt(x, indice, 0);
                       limpiar();
                        total();

                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Cantidad debe ser un numero");
            }
        }
    }
   
    private void guardar() throws UnknownHostException{
        if(tabla.getRowCount() > 0){
            if(!txtusuario.getText().isEmpty()){
                if(!txtruc.getText().isEmpty()){
                    if(!txtpedido.getText().isEmpty() && !txttimbrado.getText().isEmpty() && !txtfechafac.getText().isEmpty() && combotipo.getSelectedIndex() > -1){
                        if(JOptionPane.showConfirmDialog(null, "Desea guardar este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
                            Usuario us = udao.buscarPorNom(txtusuario.getText());
                            Proveedor prov = cdao.buscarPorId(Integer.parseInt(txtnroproveedor.getText()));
                            Factura_com ord = ordao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                            String pag = "A PAGAR";
                            if(combotipo.getSelectedItem().equals("Contado")){
                                pag = "PAGADO";
                            }
                            Nota_credito fac = new   Nota_credito(txttimbrado.getText(),f,txtfechafac.getText(),combotipo.getSelectedItem().toString(),
                                                                Integer.parseInt(txttotal.getText()),Integer.parseInt(txttotal10.getText())
                                                                ,Integer.parseInt(txttotal5.getText()),"ACTIVO",pag,ord,prov,us);
                                for (int i = 0; i < tabla.getRowCount(); i++) {
                                    Det_nota_credito dt= new Det_nota_credito();
                                    dt.setCantidad(Integer.parseInt(model.getValueAt(i, 0).toString()));
                                    dt.setPrecio(Integer.parseInt(model.getValueAt(i, 3).toString()));
                                    Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                    dt.setId_prod(p);
                                    fac.getDetalles().add(dt);
                                    dt.setId_nc(fac);
                                    
                                    int stk = p.getStock();
                                    p.setStock(stk - Integer.parseInt(model.getValueAt(i, 0).toString()));
                                    pdao.actualizar(p);
                                    
                                }
                            ncdao.guardar(fac);
                            JOptionPane.showMessageDialog(null, "Guardado correctamente");
                            ord.setEstado("REALIZADO");
                            ordao.actualizar(ord);
                            Libroiva li = new Libroiva(f, Integer.parseInt(txttotal10.getText()),Integer.parseInt(txttotal5.getText()),"credito", null,fac);
                            lidao.guardar(li);
                            arranque();
                        } 
                    }else{
                        JOptionPane.showMessageDialog(null, "Campos vacios");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Indique el cliente");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Inicie sesion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue un producto al la lista");
        }
        
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Nota_credito fac = ncdao.buscarPorId(Integer.parseInt(txtnro.getText()));
                Factura_com or = ordao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                if(fac.getEstado().equals("ACTIVO")){
                    for (int i = 0; i < tabla.getRowCount(); i++) {
                        Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        int stk = p.getStock();
                        p.setStock(stk + Integer.parseInt(model.getValueAt(i, 0).toString()));
                        pdao.actualizar(p);
                    }
                    Libroiva li = new Libroiva(f, Integer.parseInt(txttotal10.getText()),Integer.parseInt(txttotal5.getText()),"debito", null,fac);
                            lidao.guardar(li);
                    fac.setEstado("ANULADO");
                    botanular.setEnabled(false);
                    ncdao.actualizar(fac);
                    or.setEstado("ACTIVO");
                    ordao.actualizar(or);
                    txtestado.setText("ANULADO");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular");
                }
            }
        }
    }
    
    private void selecTable(){
        if(tabla.getRowCount()> 0){
            if(tabla.isEnabled()){
                if(tabla.getSelectedRow()> -1){
                   Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(tabla.getSelectedRow(),1).toString()));
                   txtnroproducto.setText(String.valueOf(p.getId_prod()));
                   txtdescripcion.setText(p.getDescripcion());
                   botquitar.setEnabled(true);
                }
            }
        }
    }
    
    private int id;
    private void id(){
       List<Nota_credito> listvn=ncdao.list();
       id=1;
       for(Nota_credito ven: listvn){
           id=ven.getId_nc()+1;
       }
       txtnro.setText(String.valueOf(id));
    }
    
    private void imprimir() throws JRException{  
         try {
            Nota_credito fc = ncdao.buscarPorId(Integer.parseInt(txtnro.getText()));
            List fac=new ArrayList();
            List<Det_nota_credito> list = fc.getDetalles(); 
            for(Det_nota_credito dt: list){
                fac.add(new fac_comreport(String.valueOf(dt.getCantidad()),String.valueOf(dt.getId_prod().getId_prod()), dt.getId_prod().getDescripcion(),
                                            String.valueOf(dt.getPrecio()), String.valueOf((dt.getCantidad()* dt.getPrecio()))));
            }       
                JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("Reportes/Factura.jasper"));
                Map<String, Object> parametro = new HashMap<String, Object>();
                parametro.put("nro",String.valueOf(fc.getId_fac()));
                parametro.put("timbrado", fc.getTimbrado());
                parametro.put("fecha", retornarString(fc.getFecha()));
                parametro.put("usser",fc.getId_us().getNombre());
                parametro.put("cliente", (fc.getId_prov().getRazon_social()));
                parametro.put("ruc", fc.getId_prov().getRuc());
                parametro.put("total",String.valueOf(fc.getTotal()));
                parametro.put("total5", String.valueOf(fc.getTotaliva5()));
                parametro.put("total10", String.valueOf(fc.getTotaliva10()));
                JasperPrint fillReport = JasperFillManager.fillReport(report, parametro ,new JRBeanCollectionDataSource(fac));
                JasperViewer jviewer = new JasperViewer(fillReport,false);
                    jviewer.setTitle("Factura de Ventas");
                    jviewer.setVisible(true);
                } catch (JRException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte."+e);        
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte."+e);
        }
        }
    
}
