/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Compras;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.Modelos.Det_pedido_compra;
import net.Modelos.Pedido_compra;
import net.Modelos.Producto;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.LoginDaoImpl;
import net.dao.Pedido_compra_daoimpl;
import net.dao.Producto_daoimpl;
import net.dao.UsuarioDaoImpl;
import net.util.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Ramc
 */
public class Pedido_compra_app extends javax.swing.JDialog {

    /**
     * Creates new form Presupuesto
     */
    public Pedido_compra_app(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque()  ;
        setLocationRelativeTo(null);
        
    }
    
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final Producto_daoimpl pdao = new Producto_daoimpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private DefaultTableModel modelpr, modelpe, model;
    private final Pedido_compra_daoimpl pedao = new Pedido_compra_daoimpl(st);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_producto = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaprod = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        filtroprod = new javax.swing.JTextField();
        agregarprod = new javax.swing.JButton();
        cancelarprod = new javax.swing.JButton();
        Buscar_Pedido = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nroped = new javax.swing.JTextField();
        botbuscarped = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        nro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        botbusprod = new javax.swing.JButton();
        botagregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        quitar = new javax.swing.JButton();
        anular = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        Buscar_producto.setSize(new java.awt.Dimension(650, 750));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Buscar Producto");

        tablaprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ));
        jScrollPane2.setViewportView(tablaprod);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filtroprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        filtroprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtroprodKeyTyped(evt);
            }
        });

        agregarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarprod.setText("Agregar");
        agregarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarprodMouseClicked(evt);
            }
        });

        cancelarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarprod.setText("Cancelar");
        cancelarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroprod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(agregarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarprod, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarprod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroprod))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_productoLayout = new javax.swing.GroupLayout(Buscar_producto.getContentPane());
        Buscar_producto.getContentPane().setLayout(Buscar_productoLayout);
        Buscar_productoLayout.setHorizontalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        Buscar_productoLayout.setVerticalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Pedido.setSize(new java.awt.Dimension(650, 750));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Buscar Pedido");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane3.setViewportView(tablaped);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpedActionPerformed(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PedidoLayout = new javax.swing.GroupLayout(Buscar_Pedido.getContentPane());
        Buscar_Pedido.getContentPane().setLayout(Buscar_PedidoLayout);
        Buscar_PedidoLayout.setHorizontalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_PedidoLayout.setVerticalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Registro de Pedidos de Compras");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        fecha.setEditable(false);
        try {
            fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(fecha);
        fecha.setBounds(610, 10, 99, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 10, 58, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 10, 68, 30);

        usuario.setEditable(false);
        usuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(usuario);
        usuario.setBounds(800, 10, 153, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro de Pedido");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 135, 30);

        nroped.setEditable(false);
        nroped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(nroped);
        nroped.setBounds(150, 10, 112, 30);

        botbuscarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarped.setText("Buscar Pedido");
        botbuscarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botbuscarpedMouseClicked(evt);
            }
        });
        botbuscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarpedActionPerformed(evt);
            }
        });
        jPanel1.add(botbuscarped);
        botbuscarped.setBounds(280, 10, 157, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Nro");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 30, 40, 30);

        nro.setEditable(false);
        nro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(nro);
        nro.setBounds(70, 30, 50, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Descripcion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(130, 30, 90, 30);

        descripcion.setEditable(false);
        descripcion.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(descripcion);
        descripcion.setBounds(210, 30, 370, 30);

        botbusprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbusprod.setText("Buscar Producto");
        botbusprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botbusprodMouseClicked(evt);
            }
        });
        botbusprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbusprodActionPerformed(evt);
            }
        });
        jPanel3.add(botbusprod);
        botbusprod.setBounds(600, 30, 130, 30);

        botagregar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botagregar.setText("Agregar Producto");
        botagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botagregarMouseClicked(evt);
            }
        });
        botagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botagregarActionPerformed(evt);
            }
        });
        jPanel3.add(botagregar);
        botagregar.setBounds(760, 30, 130, 30);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        quitar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        quitar.setText("Quitar");
        quitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarMouseClicked(evt);
            }
        });
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        anular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        anular.setText("Anular");
        anular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anularMouseClicked(evt);
            }
        });
        anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularActionPerformed(evt);
            }
        });

        estado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(anular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(anular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO", "DESCRIPCION"
            }
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(546, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botbuscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarpedActionPerformed
        buscarfactura();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarpedActionPerformed

    private void botagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botagregarActionPerformed
        agregar();// TODO add your handling code here:
    }//GEN-LAST:event_botagregarActionPerformed

    private void botbuscarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botbuscarpedMouseClicked
        
    }//GEN-LAST:event_botbuscarpedMouseClicked

    private void botbusprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botbusprodMouseClicked
        
    }//GEN-LAST:event_botbusprodMouseClicked

    private void botagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botagregarMouseClicked
        
    }//GEN-LAST:event_botagregarMouseClicked

    private void quitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarMouseClicked
        
    }//GEN-LAST:event_quitarMouseClicked

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        
    }//GEN-LAST:event_nuevoMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        
    }//GEN-LAST:event_guardarMouseClicked

    private void anularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anularMouseClicked
        
    }//GEN-LAST:event_anularMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        
    }//GEN-LAST:event_cancelarMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        selecTable();
    }//GEN-LAST:event_tablaMouseClicked

    private void agregarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarprodMouseClicked
        agregarProductos();
    }//GEN-LAST:event_agregarprodMouseClicked

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked
        retornarFactura();
    }//GEN-LAST:event_agregarpedMouseClicked

    private void cancelarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarprodActionPerformed
        Buscar_producto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarprodActionPerformed

    private void cancelarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpedActionPerformed
        Buscar_Pedido.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void botbusprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbusprodActionPerformed
        buscarproductos();// TODO add your handling code here:
    }//GEN-LAST:event_botbusprodActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        try {
            nuevo();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Pedido_compra_app.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nuevoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            guardar();
        } catch (UnknownHostException ex) {
            Logger.getLogger(Pedido_compra_app.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularActionPerformed
        anular();// TODO add your handling code here:
    }//GEN-LAST:event_anularActionPerformed

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        removerProducto();// TODO add your handling code here:
    }//GEN-LAST:event_quitarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            arranque();
        } catch (UnknownHostException ex) {
            Logger.getLogger(Pedido_compra_app.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void filtroprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroprodKeyTyped
        filtroprod.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (filtroprod.getText());//.toUpperCase();
                filtroprod.setText(cadena);
                repaint();
                filtroPr();
            }
        });
        trsfiltro = new TableRowSorter(tablaprod.getModel());
        tablaprod.setRowSorter(trsfiltro);// TODO add your handling code here:
    }//GEN-LAST:event_filtroprodKeyTyped

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tabpedidos();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido_compra_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido_compra_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido_compra_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido_compra_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pedido_compra_app dialog = null;
                try {
                    dialog = new Pedido_compra_app(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Pedido_compra_app.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Pedido;
    private javax.swing.JDialog Buscar_producto;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarprod;
    private javax.swing.JButton anular;
    private javax.swing.JButton botagregar;
    private javax.swing.JButton botbuscarped;
    private javax.swing.JButton botbusprod;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarprod;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel estado;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JTextField filtroprod;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nro;
    private javax.swing.JTextField nroped;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton quitar;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablaprod;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private Calendar f;
    private void arranque() throws UnknownHostException{
        nroped.setText(null);
        f = (Calendar.getInstance());
        fecha.setText(retornarString(f));
        nro.setText(null);
        descripcion.setText(null);
        botbusprod.setEnabled(false);
        botagregar.setEnabled(false);
        quitar.setEnabled(false);
        guardar.setEnabled(false);
        
        anular.setEnabled(false);
        estado.setText(null);
        tabla.setEnabled(true);
        nuevo.setEnabled(true);
        tableModel();
        retornarusuario();
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    usuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private void nuevo() throws UnknownHostException{
        retornarusuario();
        f = (Calendar.getInstance());
        fecha.setText(retornarString(f));
        botbusprod.setEnabled(true);
        nuevo.setEnabled(false);
        guardar.setEnabled(true);
        
    }
    private TableRowSorter trsfiltro;
    
    public void filtroPr() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtroprod.getText(), 1));
    }
    
    private void tabproductos(){
        tablaprod.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaprod.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpr = (DefaultTableModel)tablaprod.getModel();
        modelpr.setNumRows(0);
        List<Producto> list = pdao.list();
        for (Producto l : list){
            modelpr.addRow(new Object[]{
                l.getId_prod(), l.getDescripcion()
            });
        }
    }
    
    private void buscarproductos(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabproductos();
        Buscar_producto.setModal(true);
        Buscar_producto.setLocation(x,y);
        Buscar_producto.setLocationRelativeTo(null);
        Buscar_producto.setVisible(true);
    }
    
    private void agregarProductos(){
        if(tablaprod.getRowCount() > 0){
            if(tablaprod.getSelectedRow() != -1){
                Producto l = pdao.buscarPorId(Integer.parseInt(modelpr.getValueAt(tablaprod.getSelectedRow(), 0).toString()));
                nro.setText(String.valueOf(l.getId_prod()));
                descripcion.setText(l.getDescripcion());
                botagregar.setEnabled(true);
                Buscar_producto.dispose();
            }
        }
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void tabpedidos(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpe = (DefaultTableModel)tablaped.getModel();
        modelpe.setNumRows(0);
        List<Pedido_compra> list = pedao.list();
        for (Pedido_compra l : list){
            if(fechaped.getText().equals("  /  /    ")){
                modelpe.addRow(new Object[]{
                    l.getId_ped(), retornarString(l.getFecha())
                });
            
            }else{
                if(fechaped.getText().equals(retornarString(l.getFecha()))){
                    modelpe.addRow(new Object[]{
                        l.getId_ped(), retornarString(l.getFecha())
                    }); 
                }
            }
        }
    }
     
     private void buscarfactura(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabpedidos();
        Buscar_Pedido.setModal(true);
        Buscar_Pedido.setLocation(x,y);
        Buscar_Pedido.setLocationRelativeTo(null);
        Buscar_Pedido.setVisible(true);
    }
     
     private void retornarFactura(){
          if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
                Pedido_compra pe = pedao.buscarPorId(Integer.parseInt(modelpe.getValueAt(tablaped.getSelectedRow(), 0).toString()));
                fecha.setText(retornarString(pe.getFecha()));
                usuario.setText(String.valueOf(pe.getUsuarioid().getNombre()));
                nroped.setText(String.valueOf(pe.getId_ped()));
                List<Det_pedido_compra> dt =pe.getDetalles();
                model.setNumRows(0);
                tabla.setEnabled(false);
                for (Det_pedido_compra p : dt) {
                    model.addRow(new Object[]{
                        p.getCantidad(),p.getId_prod().getId_prod(),p.getId_prod().getDescripcion()
                    });
                } 
                estado.setText(pe.getEstado());
                if(estado.getText().equals("ACTIVO")){
                    anular.setEnabled(true);
                }else{
                    anular.setEnabled(false);
                }
                Buscar_Pedido.dispose();
            }
          }
    }
     
    private void limpiar(){
        nro.setText(null);
        descripcion.setText(null);
        botbusprod.setEnabled(true);
        botagregar.setEnabled(false);
        quitar.setEnabled(true);
        indice=0;
    }
    
    private int indice;
    
    private int productoAgregado(int n){
        int b = 0;
            if(tabla.getRowCount() > 0){
                for (int i = 0; i < tabla.getRowCount(); i++) {
                    if(Integer.parseInt(model.getValueAt(i, 1).toString()) != n){
                        b = 0;
                    }else{
                        b = n;
                        indice = i;
                        break;
                    }
                }
            }
        return b;
    }
    
    private boolean esNum(String n){
        boolean b;
        try{
            int x = Integer.parseInt(n);
            b=true;
        }catch (Exception e){
            b=false;
        }
        return b;
    }
    
    private void tableModel(){
    tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabla.getColumnModel().getColumn(1).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(2).setPreferredWidth(130);
    model = (DefaultTableModel)tabla.getModel();
    model.setNumRows(0);
    }
    
    
    private String can;
    private void agregar(){
        can = JOptionPane.showInputDialog("Ingrese Cantidad");
        if(esNum(can)){
            if(productoAgregado(Integer.parseInt(nro.getText())) == 0){
                model.addRow(new Object[]{
                can,nro.getText(),descripcion.getText()
                });
                limpiar();
                
            }else{
                if(JOptionPane.showConfirmDialog(null, "Desea sumar la cantidad.", "Producto ya agredado", JOptionPane.YES_OPTION) == 0){
                   int x = Integer.parseInt(can) + Integer.parseInt(model.getValueAt(indice, 0 ).toString());
                   model.setValueAt(x, indice, 0);
                   limpiar();
                   
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Cantidad debe ser un numero");
        }
    }
    
    private void removerProducto(){
        if(tabla.getRowCount() > 0){
            if(tabla.getSelectedRow() != -1){
                model.removeRow(tabla.getSelectedRow());
            }
        }
    }
    
    private void guardar() throws UnknownHostException{
        if(tabla.getRowCount() > 0){
            if(!usuario.getText().isEmpty()){
                if(JOptionPane.showConfirmDialog(null, "Desea guardar este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
                    Usuario us = udao.buscarPorNom(usuario.getText());
                    Pedido_compra pe = new Pedido_compra(f, "ACTIVO", us);
                    for (int i = 0; i < tabla.getRowCount(); i++) {
                        Det_pedido_compra dt= new Det_pedido_compra();
                        dt.setCantidad(Integer.parseInt(model.getValueAt(i, 0).toString()));
                        Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        dt.setId_prod(p);
                        pe.getDetalles().add(dt);
                        dt.setId_ped(pe);
                    }
                    pedao.guardar(pe);
                    JOptionPane.showMessageDialog(null, "Guardado correctamente");
                    arranque();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Inicie sesion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue un libro al carro de compras");
        }
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!nroped.getText().isEmpty()){
                Pedido_compra pre = pedao.buscarPorId(Integer.parseInt(nroped.getText()));
                if(pre.getEstado().equals("ACTIVO")){
                    pre.setEstado("ANULADO");
                    anular.setEnabled(false);
                    pedao.actualizar(pre);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular, El registro esta siendo utilizado en otra instancia");
                }
            }
        }
    }
    
    private void selecTable(){
        if(tabla.getRowCount()> 0){
            if(tabla.isEnabled()){
                if(tabla.getSelectedRow()> -1){
                   Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(tabla.getSelectedRow(),1).toString()));
                   nro.setText(String.valueOf(p.getId_prod()));
                   descripcion.setText(p.getDescripcion());
                }
            }
        }
    }
    
}
