/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Servicios;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.Modelos.Cliente;
import net.Modelos.Diagnostico;
import net.Modelos.Recepcion;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.ClienteDaoImpl;
import net.dao.DiagnosticoDaoImpl;
import net.dao.LoginDaoImpl;
import net.dao.RecepcionDaoImpl;
import net.dao.UsuarioDaoImpl;
import net.util.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Searp
 */
public class DiagnosticoApp extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public DiagnosticoApp(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque();
        setLocationRelativeTo(null);
    }
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final RecepcionDaoImpl rdao = new RecepcionDaoImpl(st);
    private final DiagnosticoDaoImpl ddao = new DiagnosticoDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final ClienteDaoImpl cdao = new ClienteDaoImpl(st);
    private DefaultTableModel modeldi, model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_Recepcion = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        Buscar_Diagnostico = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaped1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        agregarped1 = new javax.swing.JButton();
        cancelarped1 = new javax.swing.JButton();
        fechaped1 = new javax.swing.JFormattedTextField();
        buscarped1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtproblemas = new javax.swing.JTextField();
        txtrecomendaciones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtestadoeq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtacciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnrorec = new javax.swing.JTextField();
        botbuscarrec = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtusuariorec = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        anular = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        estado = new javax.swing.JLabel();

        Buscar_Recepcion.setSize(new java.awt.Dimension(650, 750));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Buscar Recepcion");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "CLIENTE"
            }
        ));
        jScrollPane3.setViewportView(tablaped);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpedMouseClicked(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_RecepcionLayout = new javax.swing.GroupLayout(Buscar_Recepcion.getContentPane());
        Buscar_Recepcion.getContentPane().setLayout(Buscar_RecepcionLayout);
        Buscar_RecepcionLayout.setHorizontalGroup(
            Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_RecepcionLayout.setVerticalGroup(
            Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Diagnostico.setSize(new java.awt.Dimension(650, 750));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Buscar Diagnostico");

        tablaped1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "CLIENTE"
            }
        ));
        jScrollPane4.setViewportView(tablaped1);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped1.setText("Agregar");
        agregarped1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarped1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarped1MousePressed(evt);
            }
        });

        cancelarped1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped1.setText("Cancelar");
        cancelarped1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarped1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarped1MousePressed(evt);
            }
        });

        try {
            fechaped1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        fechaped1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaped1ActionPerformed(evt);
            }
        });

        buscarped1.setText("Buscar Fecha");
        buscarped1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarped1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_DiagnosticoLayout = new javax.swing.GroupLayout(Buscar_Diagnostico.getContentPane());
        Buscar_Diagnostico.getContentPane().setLayout(Buscar_DiagnosticoLayout);
        Buscar_DiagnosticoLayout.setHorizontalGroup(
            Buscar_DiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_DiagnosticoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_DiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_DiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        Buscar_DiagnosticoLayout.setVerticalGroup(
            Buscar_DiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_DiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Diagnosticos de Equipos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(212, 24, 378, 53);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtnro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnroActionPerformed(evt);
            }
        });
        jPanel2.add(txtnro);
        txtnro.setBounds(62, 10, 90, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(botbuscar);
        botbuscar.setBounds(160, 10, 157, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(570, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtusuario);
        txtusuario.setBounds(660, 10, 153, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(370, 10, 58, 30);

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtfecha);
        txtfecha.setBounds(430, 10, 99, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 870, 60);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("Problemas detectados");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 140, 120, 30);

        txtproblemas.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtproblemas);
        txtproblemas.setBounds(150, 140, 660, 30);

        txtrecomendaciones.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtrecomendaciones);
        txtrecomendaciones.setBounds(150, 180, 660, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("Recomendaciones");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 180, 90, 30);

        txtestadoeq.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtestadoeq);
        txtestadoeq.setBounds(150, 60, 660, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Estado del dispositivo");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 60, 120, 30);

        txtacciones.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtacciones);
        txtacciones.setBounds(150, 100, 660, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Acciones Realizadas");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 100, 90, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setText("Recepcion");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 10, 70, 30);

        txtnrorec.setEditable(false);
        txtnrorec.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtnrorec);
        txtnrorec.setBounds(90, 10, 90, 30);

        botbuscarrec.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarrec.setText("Buscar");
        botbuscarrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarrecActionPerformed(evt);
            }
        });
        jPanel3.add(botbuscarrec);
        botbuscarrec.setBounds(190, 10, 157, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setText("Usuario");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(380, 10, 68, 30);

        txtusuariorec.setEditable(false);
        txtusuariorec.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtusuariorec);
        txtusuariorec.setBounds(430, 10, 153, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 140, 870, 230);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel14.setText("Nro");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 20, 50, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("RUC");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(150, 20, 50, 30);

        txtruc.setEditable(false);
        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });
        jPanel5.add(txtruc);
        txtruc.setBounds(200, 20, 130, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel16.setText("Razon Social");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(350, 20, 70, 30);

        txtrazonsocial.setEditable(false);
        txtrazonsocial.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(txtrazonsocial);
        txtrazonsocial.setBounds(420, 20, 310, 30);

        txtcliente.setEditable(false);
        txtcliente.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(txtcliente);
        txtcliente.setBounds(80, 20, 50, 30);
        jPanel5.add(jLabel17);
        jLabel17.setBounds(1090, -120, 52, 900);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 380, 870, 90);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        nuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        nuevo.setText("NUEVO");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        guardar.setText("GUARDAR");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        anular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        anular.setText("ANULAR");
        anular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anularMouseClicked(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        salir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        estado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 480, 870, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarDiagnostico(); // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botbuscarrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarrecActionPerformed
       buscarPresupuesto(); // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarrecActionPerformed

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        nuevo();
    }//GEN-LAST:event_nuevoMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        try {
            guardar();
        } catch (UnknownHostException ex) {
            Logger.getLogger(DiagnosticoApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarMouseClicked

    private void anularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anularMouseClicked
        anular();
    }//GEN-LAST:event_anularMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        try {
            arranque();
        } catch (UnknownHostException ex) {
            Logger.getLogger(DiagnosticoApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void txtnroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroActionPerformed

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked
        retornarPresupuesto();
    }//GEN-LAST:event_agregarpedMouseClicked

    private void cancelarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpedMouseClicked
        Buscar_Recepcion.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedMouseClicked

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    private void agregarped1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarped1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarped1MouseClicked

    private void cancelarped1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarped1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarped1MouseClicked

    private void buscarped1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarped1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarped1ActionPerformed

    private void fechaped1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaped1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaped1ActionPerformed

    private void agregarped1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarped1MousePressed
        retornarDiagnostico();// TODO add your handling code here:
    }//GEN-LAST:event_agregarped1MousePressed

    private void cancelarped1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarped1MousePressed
       Buscar_Diagnostico.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_cancelarped1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagnosticoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagnosticoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagnosticoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagnosticoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagnosticoApp dialog = null;
                try {
                    dialog = new DiagnosticoApp(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(DiagnosticoApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Diagnostico;
    private javax.swing.JDialog Buscar_Recepcion;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarped1;
    private javax.swing.JButton anular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botbuscarrec;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton buscarped1;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarped1;
    private javax.swing.JLabel estado;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JFormattedTextField fechaped1;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablaped1;
    private javax.swing.JTextField txtacciones;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtestadoeq;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnrorec;
    private javax.swing.JTextField txtproblemas;
    private javax.swing.JTextField txtrazonsocial;
    private javax.swing.JTextField txtrecomendaciones;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JTextField txtusuariorec;
    // End of variables declaration//GEN-END:variables

private Calendar f;
    private void arranque() throws UnknownHostException{
    //campos
    txtfecha.setEnabled(false);
    estado.setText(null);
    f = (Calendar.getInstance());
    txtfecha.setText(retornarString(f));
    txtnro.setEnabled(false);
    txtnro.setText(null);
    txtruc.setEnabled(false);
    txtruc.setText(null);
    txtcliente.setText(null);
    txtrazonsocial.setText(null);
    txtestadoeq.setText(null);
    txtestadoeq.setEnabled(false);
    txtacciones.setText(null);
    txtacciones.setEnabled(false);
    txtproblemas.setText(null);
    txtproblemas.setEnabled(false);
    txtrecomendaciones.setText(null);
    txtrecomendaciones.setEnabled(false);
    txtnrorec.setText(null);
    txtnrorec.setEnabled(false);
    txtusuariorec.setText(null);
    txtusuariorec.setEnabled(false);
    
    //botones
    botbuscarrec.setEnabled(false);
    botbuscar.setEnabled(true);
    nuevo.setEnabled(true);
    guardar.setEnabled(false);
    guardar.setText("Guardar");
    anular.setEnabled(false);
    
    retornarusuario();
    }
    
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private String hostname;
    
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private void nuevo(){
     //campos
     estado.setText(null);
     txtestadoeq.setEnabled(true);
     txtacciones.setEnabled(true);
     txtproblemas.setEnabled(true);
     txtrecomendaciones.setEnabled(true);
    //botones
    nuevo.setEnabled(false);
    guardar.setEnabled(true);
    guardar.setText("Guardar");
    anular.setEnabled(false);
    botbuscar.setEnabled(false);
    botbuscarrec.setEnabled(true);
    }
    
    private TableRowSorter trsfiltro;
    
    private void tablaPresupuesto(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablaped.getColumnModel().getColumn(2).setPreferredWidth(180);
        model = (DefaultTableModel)tablaped.getModel();
        model.setNumRows(0);
        List<Recepcion> list = rdao.list();
        for (Recepcion l : list){
            if(l.getEstado().equals("ACTIVO")){
            if(fechaped.getText().equals("  /  /    ")){
            
                model.addRow(new Object[]{
                   l.getId_rec(), retornarString(l.getFecha()),l.getCliente().getRazon_social()
                    
                    });
            
            }else{
               if(fechaped.getText().equals(retornarString(l.getFecha()))){
                   model.addRow(new Object[]{
                l.getId_rec(), retornarString(l.getFecha()),l.getCliente().getRazon_social()
            }); 
               }
            }
            }
        }   
    }
     
    private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Recepcion.setModal(true);
        Buscar_Recepcion.setLocation(x,y);
        Buscar_Recepcion.setLocationRelativeTo(null);
        Buscar_Recepcion.setVisible(true);
    }
     
    private void retornarPresupuesto(){
        if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
                Recepcion r = rdao.buscarPorId(Integer.parseInt(model.getValueAt(tablaped.getSelectedRow(), 0).toString()));
                txtusuariorec.setText(String.valueOf(r.getUsuario().getNombre()));
                txtnrorec.setText(String.valueOf(r.getId_rec()));
                txtcliente.setText(String.valueOf(r.getCliente().getId_clie()));
                txtruc.setText(String.valueOf(r.getCliente().getRuc()));
                txtrazonsocial.setText(String.valueOf(r.getCliente().getRazon_social()));
        
                Buscar_Recepcion.dispose();
                botbuscar.setEnabled(false);
            }
        }
    }
    
    
    private void tablaDiagnostico(){
        tablaped1.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped1.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablaped1.getColumnModel().getColumn(2).setPreferredWidth(180);
        modeldi = (DefaultTableModel)tablaped1.getModel();
        modeldi.setNumRows(0);
        List<Diagnostico> list = ddao.list();
        for (Diagnostico l : list){
            if(fechaped1.getText().equals("  /  /    ")){
               modeldi.addRow(new Object[]{
                l.getId_diag(), retornarString(l.getFecha()),l.getRecepcion().getCliente().getRazon_social()
            }); 
            }else{
               if(fechaped1.getText().equals(retornarString(l.getFecha()))){
                   modeldi.addRow(new Object[]{
                l.getId_diag(), retornarString(l.getFecha()),l.getRecepcion().getCliente().getRazon_social()
            }); 
               }
            }
            
        }
    }
     
     private void buscarDiagnostico(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaDiagnostico();
        Buscar_Diagnostico.setModal(true);
        Buscar_Diagnostico.setLocation(x,y);
        Buscar_Diagnostico.setLocationRelativeTo(null);
        Buscar_Diagnostico.setVisible(true);
    }
     
    private void retornarDiagnostico(){
        if(tablaped1.getRowCount() > 0){
            if(tablaped1.getSelectedRow() != -1){
                Diagnostico r = ddao.buscarPorId(Integer.parseInt(modeldi.getValueAt(tablaped1.getSelectedRow(), 0).toString()));
                txtfecha.setText(retornarString(r.getFecha()));
                txtusuario.setText(String.valueOf(r.getUsuario().getNombre()));
                txtnro.setText(String.valueOf(r.getId_diag()));
                txtcliente.setText(String.valueOf(r.getRecepcion().getCliente().getId_clie()));
                txtruc.setText(String.valueOf(r.getRecepcion().getCliente().getRuc()));
                txtrazonsocial.setText(String.valueOf(r.getRecepcion().getCliente().getRazon_social()));
                
                txtestadoeq.setText(String.valueOf(r.getEstadodisp()));
                txtacciones.setText(String.valueOf(r.getAcciones()));
                txtproblemas.setText(String.valueOf(r.getProblemas()));
                txtrecomendaciones.setText(String.valueOf(r.getRecomendaciones()));
                
                txtnrorec.setText(String.valueOf(r.getRecepcion().getId_rec()));
                txtusuariorec.setText(String.valueOf(r.getRecepcion().getUsuario().getNombre()));

                Buscar_Diagnostico.dispose();
                botbuscar.setEnabled(false);
                estado.setText(r.getEstado());

                if(r.getEstado().equals("ACTIVO")){
                    anular.setEnabled(true);
                }else{
                    anular.setEnabled(false);
                }
            }
        }
    }
     
    private void guardar() throws UnknownHostException{
        if(!txtruc.getText().isEmpty() && !txtestadoeq.getText().isEmpty() && !txtacciones.getText().isEmpty() 
                && !txtproblemas.getText().isEmpty() && !txtrecomendaciones.getText().isEmpty()&& !txtnrorec.getText().isEmpty()){
                    Usuario us = udao.buscarPorNom(txtusuario.getText());
                    Recepcion rec = rdao.buscarPorId(Integer.parseInt(txtnrorec.getText()));
                    Diagnostico r = new Diagnostico(f,txtestadoeq.getText(),txtacciones.getText(),txtproblemas.getText(),txtrecomendaciones.getText(),us,rec,"ACTIVO");
                        ddao.guardar(r);
                        JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
                        arranque();  
        }else{
            JOptionPane.showMessageDialog(null, "Campo vacio. Rellene correctamente");
        }
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Diagnostico r = ddao.buscarPorId(Integer.parseInt(txtnro.getText()));
                if(r.getEstado().equals("ACTIVO")){
                    r.setEstado("ANULADO");
                    anular.setEnabled(false);
                    ddao.actualizar(r);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular este registro. Esta siendo utilizado en otra instancia");
                }
            }
        }
    }
    
    
}
