/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Servicios;

import Reportes.fac_comreport;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.Modelos.Det_pedido_compra;
import net.Modelos.Det_presupuesto_serv;
import net.Modelos.Diagnostico;
import net.Modelos.Presupuesto_serv;
import net.Modelos.Producto;
import net.Modelos.Cliente;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.Det_presupuesto_prod_daoimpl;
import net.dao.LoginDaoImpl;
import net.dao.DiagnosticoDaoImpl;
import net.dao.Presupuesto_serv_daoimpl;
import net.dao.Producto_daoimpl;
import net.dao.ClienteDaoImpl;
import net.dao.UsuarioDaoImpl;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.util.HibernateUtil;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author Ramc
 */
public class Presupuesto_servApp extends javax.swing.JDialog {

    /**
     * Creates new form Presupuesto
     */
    public Presupuesto_servApp(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque()  ;
        setLocationRelativeTo(null);
    }
    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final Producto_daoimpl pdao = new Producto_daoimpl(st);
    private final ClienteDaoImpl cdao = new ClienteDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final DiagnosticoDaoImpl ddao = new DiagnosticoDaoImpl(st);
    private final Presupuesto_serv_daoimpl presdao = new Presupuesto_serv_daoimpl(st);
    private final Det_presupuesto_prod_daoimpl dtdao = new Det_presupuesto_prod_daoimpl(st);
    private DefaultTableModel modelpr,modelclie, modelpres, model, modelpe;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_producto = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaprod = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        filtroprod = new javax.swing.JTextField();
        agregarprod = new javax.swing.JButton();
        cancelarprod = new javax.swing.JButton();
        Buscar_Presupuesto = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablapres = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        agregarpres = new javax.swing.JButton();
        cancelarpres = new javax.swing.JButton();
        fechapres = new javax.swing.JFormattedTextField();
        buscarpres = new javax.swing.JButton();
        Buscar_Pedido = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtnroproducto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        botagregar = new javax.swing.JButton();
        botbuscarproducto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botnuevo = new javax.swing.JButton();
        botguardar = new javax.swing.JButton();
        botsalir = new javax.swing.JButton();
        botcancelar = new javax.swing.JButton();
        botquitar = new javax.swing.JButton();
        botanular = new javax.swing.JButton();
        txtestado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        txtnroproveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        botimprimir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtpedido = new javax.swing.JTextField();
        botbuscarpedido = new javax.swing.JButton();
        txtfechapedido = new javax.swing.JFormattedTextField();
        txtusuariopedido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        Buscar_producto.setResizable(false);
        Buscar_producto.setSize(new java.awt.Dimension(650, 750));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Buscar Producto");

        tablaprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ));
        jScrollPane2.setViewportView(tablaprod);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filtroprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        filtroprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtroprodKeyTyped(evt);
            }
        });

        agregarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarprod.setText("Agregar");
        agregarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarprodMouseClicked(evt);
            }
        });
        agregarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarprodActionPerformed(evt);
            }
        });

        cancelarprod.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarprod.setText("Cancelar");
        cancelarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarprodMouseClicked(evt);
            }
        });
        cancelarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroprod, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(agregarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarprod, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarprod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtroprod))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_productoLayout = new javax.swing.GroupLayout(Buscar_producto.getContentPane());
        Buscar_producto.getContentPane().setLayout(Buscar_productoLayout);
        Buscar_productoLayout.setHorizontalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        Buscar_productoLayout.setVerticalGroup(
            Buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Presupuesto.setSize(new java.awt.Dimension(650, 750));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Buscar Presupuesto");

        tablapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablapres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "PROVEEDOR"
            }
        ));
        jScrollPane3.setViewportView(tablapres);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarpres.setText("Agregar");
        agregarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarpresMouseEntered(evt);
            }
        });
        agregarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpresActionPerformed(evt);
            }
        });

        cancelarpres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarpres.setText("Cancelar");
        cancelarpres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpresMouseClicked(evt);
            }
        });
        cancelarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpresActionPerformed(evt);
            }
        });

        try {
            fechapres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechapres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechapres.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarpres.setText("Buscar Fecha");
        buscarpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechapres, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarpres, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarpres, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarpres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechapres, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PresupuestoLayout = new javax.swing.GroupLayout(Buscar_Presupuesto.getContentPane());
        Buscar_Presupuesto.getContentPane().setLayout(Buscar_PresupuestoLayout);
        Buscar_PresupuestoLayout.setHorizontalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_PresupuestoLayout.setVerticalGroup(
            Buscar_PresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Pedido.setSize(new java.awt.Dimension(650, 750));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Buscar Diagnostico");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NRO", "FECHA"
            }
        ));
        jScrollPane5.setViewportView(tablaped);

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });
        agregarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarpedActionPerformed(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarpedActionPerformed(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_PedidoLayout = new javax.swing.GroupLayout(Buscar_Pedido.getContentPane());
        Buscar_Pedido.getContentPane().setLayout(Buscar_PedidoLayout);
        Buscar_PedidoLayout.setHorizontalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        Buscar_PedidoLayout.setVerticalGroup(
            Buscar_PedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_PedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Registro de Presupuesto de Servicios");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtfecha);
        txtfecha.setBounds(610, 10, 99, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(550, 10, 58, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(730, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtusuario);
        txtusuario.setBounds(800, 10, 153, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro de Presupuesto");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 135, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel1.add(txtnro);
        txtnro.setBounds(150, 10, 112, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar Presupuesto");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botbuscar);
        botbuscar.setBounds(280, 10, 157, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Nro");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 30, 40, 30);

        txtnroproducto.setEditable(false);
        txtnroproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtnroproducto);
        txtnroproducto.setBounds(70, 30, 50, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Descripcion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(130, 30, 90, 30);

        txtdescripcion.setEditable(false);
        txtdescripcion.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtdescripcion);
        txtdescripcion.setBounds(210, 30, 370, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setText("Precio");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(760, 30, 80, 30);

        txtprecio.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtprecio);
        txtprecio.setBounds(810, 30, 120, 30);

        botagregar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botagregar.setText("Agregar Producto");
        botagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botagregarActionPerformed(evt);
            }
        });
        jPanel3.add(botagregar);
        botagregar.setBounds(940, 30, 130, 30);

        botbuscarproducto.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarproducto.setText("Buscar Producto");
        botbuscarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botbuscarproductoMouseClicked(evt);
            }
        });
        botbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarproductoActionPerformed(evt);
            }
        });
        jPanel3.add(botbuscarproducto);
        botbuscarproducto.setBounds(610, 30, 130, 30);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botnuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botnuevo.setText("Nuevo");
        botnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnuevoActionPerformed(evt);
            }
        });

        botguardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botguardar.setText("Guardar");
        botguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botguardarActionPerformed(evt);
            }
        });

        botsalir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botsalir.setText("Salir");
        botsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalirActionPerformed(evt);
            }
        });

        botcancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botcancelar.setText("Cancelar");
        botcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcancelarActionPerformed(evt);
            }
        });

        botquitar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botquitar.setText("Quitar");
        botquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botquitarActionPerformed(evt);
            }
        });

        botanular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botanular.setText("Anular");
        botanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botanularActionPerformed(evt);
            }
        });

        txtestado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510)
                .addComponent(botquitar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botcancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(428, 428, 428)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(428, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botanular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botquitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("Nro");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 20, 50, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("RUC");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 20, 50, 30);

        txtruc.setEditable(false);
        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });
        jPanel2.add(txtruc);
        txtruc.setBounds(200, 20, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Razon Social");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 20, 80, 30);

        txtrazonsocial.setEditable(false);
        txtrazonsocial.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtrazonsocial);
        txtrazonsocial.setBounds(500, 20, 310, 30);

        txtnroproveedor.setEditable(false);
        txtnroproveedor.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtnroproveedor);
        txtnroproveedor.setBounds(80, 20, 50, 30);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(1090, -120, 52, 900);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO", "DESCRIPCION", "PRECIO", "TOTAL"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("TOTAL");

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        botimprimir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botimprimir.setText("Imprimir");
        botimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botimprimirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Diagnostico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel12.setText("Nro de Diagnostico");

        txtpedido.setEditable(false);
        txtpedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpedidoActionPerformed(evt);
            }
        });

        botbuscarpedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarpedido.setText("Buscar ");
        botbuscarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarpedidoActionPerformed(evt);
            }
        });

        txtfechapedido.setEditable(false);
        try {
            txtfechapedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfechapedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfechapedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        txtusuariopedido.setEditable(false);
        txtusuariopedido.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel22.setText("Usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botbuscarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(txtfechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtusuariopedido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botbuscarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuariopedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(273, 273, 273)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    private void botimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botimprimirActionPerformed
        try {
            imprimir();        // TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(Presupuesto_servApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botimprimirActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpedidoActionPerformed

    private void filtroprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroprodKeyTyped
        filtroprod.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (filtroprod.getText());//.toUpperCase();
                filtroprod.setText(cadena);
                repaint();
                filtroPr();
            }
        });
        trsfiltro = new TableRowSorter(tablaprod.getModel());
        tablaprod.setRowSorter(trsfiltro);// TODO add your handling code here:
    }//GEN-LAST:event_filtroprodKeyTyped

    private void agregarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarprodMouseClicked
        
    }//GEN-LAST:event_agregarprodMouseClicked

    private void cancelarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarprodMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarprodMouseClicked

    private void agregarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseClicked
        
    }//GEN-LAST:event_agregarpresMouseClicked

    private void cancelarpresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpresMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresMouseClicked

    private void buscarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpresActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpresActionPerformed

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked
        
    }//GEN-LAST:event_agregarpedMouseClicked

    private void cancelarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpedActionPerformed
        Buscar_Pedido.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedActionPerformed

    private void botbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarproductoActionPerformed
        buscarproductos();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarproductoActionPerformed

    private void botbuscarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botbuscarproductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botbuscarproductoMouseClicked

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tabpedidos();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    private void agregarpresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarpresMouseEntered

    private void agregarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpresActionPerformed
        retornarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpresActionPerformed

    private void cancelarpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarpresActionPerformed
         Buscar_Presupuesto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpresActionPerformed

    private void agregarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarprodActionPerformed
        agregarProductos();// TODO add your handling code here:
    }//GEN-LAST:event_agregarprodActionPerformed

    private void cancelarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarprodActionPerformed
        Buscar_producto.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarprodActionPerformed

    private void agregarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarpedActionPerformed
        retornarFactura();// TODO add your handling code here:
    }//GEN-LAST:event_agregarpedActionPerformed

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarActionPerformed

    private void botbuscarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarpedidoActionPerformed
        buscarfactura();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarpedidoActionPerformed

    private void botagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botagregarActionPerformed
        agregar();// TODO add your handling code here:
    }//GEN-LAST:event_botagregarActionPerformed

    private void botnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnuevoActionPerformed
        try {
            nuevo();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Presupuesto_servApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botnuevoActionPerformed

    private void botguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botguardarActionPerformed
        try {
            guardar();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Presupuesto_servApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botguardarActionPerformed

    private void botanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botanularActionPerformed
        anular();// TODO add your handling code here:
    }//GEN-LAST:event_botanularActionPerformed

    private void botquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botquitarActionPerformed
        removerProducto();// TODO add your handling code here:
    }//GEN-LAST:event_botquitarActionPerformed

    private void botcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcancelarActionPerformed
        try {
            arranque();// TODO add your handling code here:
        } catch (UnknownHostException ex) {
            Logger.getLogger(Presupuesto_servApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botcancelarActionPerformed

    private void botsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalirActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_botsalirActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        selecTable();// TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presupuesto_servApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presupuesto_servApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presupuesto_servApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presupuesto_servApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Presupuesto_servApp dialog = null;
                try {
                    dialog = new Presupuesto_servApp(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Presupuesto_servApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Pedido;
    private javax.swing.JDialog Buscar_Presupuesto;
    private javax.swing.JDialog Buscar_producto;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton agregarpres;
    private javax.swing.JButton agregarprod;
    private javax.swing.JButton botagregar;
    private javax.swing.JButton botanular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botbuscarpedido;
    private javax.swing.JButton botbuscarproducto;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton botguardar;
    private javax.swing.JButton botimprimir;
    private javax.swing.JButton botnuevo;
    private javax.swing.JButton botquitar;
    private javax.swing.JButton botsalir;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton buscarpres;
    private javax.swing.JButton cancelarped;
    private javax.swing.JButton cancelarpres;
    private javax.swing.JButton cancelarprod;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JFormattedTextField fechapres;
    private javax.swing.JTextField filtroprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaped;
    private javax.swing.JTable tablapres;
    private javax.swing.JTable tablaprod;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txtestado;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JFormattedTextField txtfechapedido;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnroproducto;
    private javax.swing.JTextField txtnroproveedor;
    private javax.swing.JTextField txtpedido;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtrazonsocial;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JTextField txtusuariopedido;
    // End of variables declaration//GEN-END:variables
    
    private Calendar f;
    private void arranque() throws UnknownHostException{
        txtnro.setText(null);
        txtestado.setText(null);
        txttotal.setText(null);
        txtnro.setEnabled(false);
        txtnroproducto.setText(null);
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        txtnroproveedor.setText(null);
        txtruc.setText(null);
        txtrazonsocial.setText(null);
        txtdescripcion.setText(null);
        txtprecio.setText(null);
        txtprecio.setEnabled(false);
        botbuscar.setEnabled(true);
        botbuscarpedido.setEnabled(false);
        botbuscarproducto.setEnabled(false);
        botagregar.setEnabled(false);
        botquitar.setEnabled(false);
        botguardar.setEnabled(false);
        txtpedido.setText(null);
        txtusuariopedido.setText(null);
        txtfechapedido.setText(null);
        
        botanular.setEnabled(false);
        tabla.setEnabled(true);
        botnuevo.setEnabled(true);
        tableModel();
        retornarusuario();
    }
    
    private String hostname;
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private void nuevo() throws UnknownHostException{
        f = (Calendar.getInstance());
        txtfecha.setText(retornarString(f));
        retornarusuario();
        tabla.setEnabled(true);
        botbuscar.setEnabled(false);
        botnuevo.setEnabled(false);
        botbuscarpedido.setEnabled(true); 
        botguardar.setEnabled(true);
        id();
    }
    
    private TableRowSorter trsfiltro;
    public void filtroPr() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(filtroprod.getText(), 1));
    }
    
    
    
    private void tabproductos(){
        tablaprod.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaprod.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpr = (DefaultTableModel)tablaprod.getModel();
        modelpr.setNumRows(0);
        List<Producto> list = pdao.list();
        for (Producto l : list){
            
            modelpr.addRow(new Object[]{
                l.getId_prod(), l.getDescripcion()
            });
          
        }
    }
    
    private void buscarproductos(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabproductos();
        Buscar_producto.setModal(true);
        Buscar_producto.setLocation(x,y);
        Buscar_producto.setLocationRelativeTo(null);
        Buscar_producto.setVisible(true);
    }
    
    private void agregarProductos(){
        if(tablaprod.getRowCount() > 0){
            if(tablaprod.getSelectedRow() != -1){
                Producto l = pdao.buscarPorId(Integer.parseInt(modelpr.getValueAt(tablaprod.getSelectedRow(), 0).toString()));
                txtnroproducto.setText(String.valueOf(l.getId_prod()));
                txtdescripcion.setText(l.getDescripcion());
                txtprecio.setText(String.valueOf(l.getPrecio()));
                botagregar.setEnabled(true);
                Buscar_producto.dispose();
            }
        }
    }
    
    private void tabpedidos(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelpe = (DefaultTableModel)tablaped.getModel();
        modelpe.setNumRows(0);
        List<Diagnostico> list = ddao.list();
        for (Diagnostico l : list){
            
            if(l.getEstado().equals("ACTIVO")){
               if(fechaped.getText().equals("  /  /    ")){
                    modelpe.addRow(new Object[]{
                    l.getId_diag(), retornarString(l.getFecha())
                    }); 
               }else{
                   if(fechaped.getText().equals(retornarString(l.getFecha()))){
                        modelpe.addRow(new Object[]{
                        l.getId_diag(), retornarString(l.getFecha())
                        }); 
                   }
               }
            }
           
            
        }
    }
     
     private void buscarfactura(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabpedidos();
        Buscar_Pedido.setModal(true);
        Buscar_Pedido.setLocation(x,y);
        Buscar_Pedido.setLocationRelativeTo(null);
        Buscar_Pedido.setVisible(true);
    }
     
    private void retornarFactura(){
          if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
                Diagnostico pe = ddao.buscarPorId(Integer.parseInt(modelpe.getValueAt(tablaped.getSelectedRow(), 0).toString()));
                txtfechapedido.setText(retornarString(pe.getFecha()));
                txtusuariopedido.setText(String.valueOf(pe.getUsuario().getNombre()));
                txtpedido.setText(String.valueOf(pe.getId_diag()));
                txtnroproveedor.setText(String.valueOf(pe.getRecepcion().getCliente().getId_clie()));
                txtruc.setText(String.valueOf(pe.getRecepcion().getCliente().getRuc()));
                txtrazonsocial.setText(String.valueOf(pe.getRecepcion().getCliente().getRazon_social()));
                Buscar_Pedido.dispose();
                tabla.setEnabled(true);
                botbuscarproducto.setEnabled(true);
            }
          }   
    }
    
    
    private void tablaPresupuesto(){
        tablapres.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablapres.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablapres.getColumnModel().getColumn(2).setPreferredWidth(180);
        modelpres = (DefaultTableModel)tablapres.getModel();
        modelpres.setNumRows(0);
        List<Presupuesto_serv> list = presdao.list();
        for (Presupuesto_serv l : list){
            if(fechapres.getText().equals("  /  /    ")){
               modelpres.addRow(new Object[]{
                l.getId_pres(),retornarString(l.getFecha()),l.getId_prov().getRazon_social()
            }); 
            }else{
               if(fechapres.getText().equals(retornarString(l.getFecha()))){
                   modelpres.addRow(new Object[]{
                l.getId_pres(), retornarString(l.getFecha()),l.getId_prov().getRazon_social()
            }); 
               }
            }
            
        }
    }
     
     private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Presupuesto.setModal(true);
        Buscar_Presupuesto.setLocation(x,y);
        Buscar_Presupuesto.setLocationRelativeTo(null);
        Buscar_Presupuesto.setVisible(true);
    }
     
     
    private void retornarPresupuesto(){
        if(tablapres.getRowCount() > 0){
            if(tablapres.getSelectedRow() != -1){
            Presupuesto_serv pe = presdao.buscarPorId(Integer.parseInt(modelpres.getValueAt(tablapres.getSelectedRow(), 0).toString()));
            txtfecha.setText(retornarString(pe.getFecha()));
            txtusuario.setText(String.valueOf(pe.getId_us().getNombre()));
            txtpedido.setText(String.valueOf(pe.getId_ped().getId_diag()));
            txtfechapedido.setText(String.valueOf(retornarString(pe.getId_ped().getFecha())));
            txtusuariopedido.setText(String.valueOf(pe.getId_ped().getUsuario().getNombre()));
            txtnro.setText(String.valueOf(pe.getId_pres()));
            txtnroproveedor.setText(String.valueOf(pe.getId_prov().getId_clie()));
            txtruc.setText(String.valueOf(pe.getId_prov().getRuc()));
            txtrazonsocial.setText(String.valueOf(pe.getId_prov().getRazon_social()));
            List<Det_presupuesto_serv> dt =pe.getDetalles();
            model.setNumRows(0);
            tabla.setEnabled(false);
            for (Det_presupuesto_serv p : dt) {
                model.addRow(new Object[]{
                    p.getCantidad(),p.getId_prod().getId_prod(),p.getId_prod().getDescripcion(),p.getPrecio(),(p.getCantidad() * p.getPrecio())
                });
            } 
            botnuevo.setEnabled(false);
            Buscar_Presupuesto.dispose();
            botbuscar.setEnabled(false);
            txtestado.setText(pe.getEstado());

            if(pe.getEstado().equals("ACTIVO")){
                botanular.setEnabled(true);
            }else{
                botanular.setEnabled(false);
            }

             total();
            }
        }
    }
     
    private void limpiar(){
        txtnroproducto.setText(null);
        txtdescripcion.setText(null);
        txtprecio.setText(null);
        botbuscarproducto.setEnabled(true);
        botagregar.setEnabled(false);
        botquitar.setEnabled(true);
        indice=0;
    }
    
    private int indice;
    private int productoAgregado(int n){
        int b = 0;
            if(tabla.getRowCount() > 0){
                for (int i = 0; i < tabla.getRowCount(); i++) {
                    if(Integer.parseInt(model.getValueAt(i, 1).toString()) != n){
                        b = 0;
                    }else{
                        b = n;
                        indice = i;
                        break;
                    }
                }
            }
        return b;
    }
    
    private boolean esNum(String n){
        boolean b;
        try{
            int x = Integer.parseInt(n);
            b=true;
        }catch (Exception e){
            b=false;
        }
        return b;
    }
    
    private void tableModel(){
    tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
    tabla.getColumnModel().getColumn(1).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(2).setPreferredWidth(130);
    tabla.getColumnModel().getColumn(3).setPreferredWidth(230);
    tabla.getColumnModel().getColumn(4).setPreferredWidth(130);
    model = (DefaultTableModel)tabla.getModel();
    model.setNumRows(0);
    }
    
    private void total(){
        txttotal.setText(null);
        int tot=0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tot= tot + (Integer.parseInt(model.getValueAt(i, 4).toString()));
        }
        txttotal.setText(String.valueOf(tot));
    }
    
    private String can;
    private void agregar(){
        
            if(productoAgregado(Integer.parseInt(txtnroproducto.getText())) == 0){
                can = JOptionPane.showInputDialog("Ingrese Cantidad");
                if(esNum(can)){
                    model.addRow(new Object[]{
                    can,txtnroproducto.getText(),txtdescripcion.getText(),txtprecio.getText(),Integer.parseInt(can)*Integer.parseInt(txtprecio.getText())
                    });
                    limpiar();
                    total();
                }else{
                    JOptionPane.showMessageDialog(null, "Cantidad debe ser un numero");
                }  
            }else{
                   int x = Integer.parseInt(model.getValueAt(indice, 0 ).toString());
                   int y = Integer.parseInt(txtprecio.getText()) * x;
                   int z = Integer.parseInt(txtprecio.getText());
                   model.setValueAt(z,indice,3);
                   model.setValueAt(y, indice, 4);
                   limpiar();
                   total();
            }
        
    }
    
    private void removerProducto(){
        if(tabla.getRowCount() > 0){
            if(tabla.getSelectedRow() != -1){
                model.removeRow(tabla.getSelectedRow());
            }
        }
        total();
    }
    
    private void guardar() throws UnknownHostException{
        if(tabla.getRowCount() > 0){
            if(!txtusuario.getText().isEmpty()){
                if(!txtruc.getText().isEmpty()){
                    if(!txtpedido.getText().isEmpty()){
                        if(JOptionPane.showConfirmDialog(null, "Desea guardar este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
                            Usuario us = udao.buscarPorNom(txtusuario.getText());
                            Cliente cl = cdao.buscarPorId(Integer.parseInt(txtnroproveedor.getText()));
                            Diagnostico pc = ddao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                            Presupuesto_serv pre = new   Presupuesto_serv(f,"ACTIVO", pc, us, cl);
                                for (int i = 0; i < tabla.getRowCount(); i++) {
                                    Det_presupuesto_serv dt= new Det_presupuesto_serv();
                                    dt.setCantidad(Integer.parseInt(model.getValueAt(i, 0).toString()));
                                    dt.setPrecio(Integer.parseInt(model.getValueAt(i, 3).toString()));
                                    Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                    dt.setId_prod(p);
                                    pre.getDetalles().add(dt);
                                    dt.setId_pres(pre);
                                }
                            presdao.guardar(pre);
                            JOptionPane.showMessageDialog(null, "Guardado correctamente");
                            pc.setEstado("REALIZADO");
                            ddao.actualizar(pc);
                            arranque();
                        } 
                    }else{
                        JOptionPane.showMessageDialog(null, "Ingrese un numero de Pedido");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Indique el cliente");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Inicie sesion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Agregue un producto al la lista");
        }
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Presupuesto_serv pre = presdao.buscarPorId(Integer.parseInt(txtnro.getText()));
                Diagnostico ped = ddao.buscarPorId(Integer.parseInt(txtpedido.getText()));
                if(pre.getEstado().equals("ACTIVO")){
                    pre.setEstado("ANULADO");
                    botanular.setEnabled(false);
                    presdao.actualizar(pre);
                    ped.setEstado("ACTIVO");
                    ddao.actualizar(ped);
                    txtestado.setText("ANULADO");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular un presupuesto REALIZADO");
                }
            }
        }
    }
    
    private void selecTable(){
        if(tabla.getRowCount()> 0){
            if(tabla.isEnabled()){
                if(tabla.getSelectedRow()> -1){
                   Producto p = pdao.buscarPorId(Integer.parseInt(model.getValueAt(tabla.getSelectedRow(),1).toString()));
                   txtnroproducto.setText(String.valueOf(p.getId_prod()));
                   txtdescripcion.setText(p.getDescripcion());
                   txtprecio.setEnabled(true);
                   botagregar.setEnabled(true);
                }
            }
        }
    }
    
    private int id;
    private void id(){
       List<Presupuesto_serv> listvn=presdao.list();
       id=0;
       for(Presupuesto_serv ven: listvn){
           id=ven.getId_pres()+1;
       }
       txtnro.setText(String.valueOf(id));
    }
    
    private void imprimir() throws JRException{  
         try {
            Presupuesto_serv fc = presdao.buscarPorId(Integer.parseInt(txtnro.getText()));
            List fac=new ArrayList();
            List<Det_presupuesto_serv> list = fc.getDetalles(); 
            for(Det_presupuesto_serv dt: list){
                fac.add(new fac_comreport(String.valueOf(dt.getCantidad()),String.valueOf(dt.getId_prod().getId_prod()), dt.getId_prod().getDescripcion(),
                                            String.valueOf(dt.getPrecio()), String.valueOf((dt.getCantidad()* dt.getPrecio()))));
            }       
                JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("Reportes/Presupuesto_2.jasper"));
                Map<String, Object> parametro = new HashMap<String, Object>();
                parametro.put("nro",String.valueOf(fc.getId_pres()));
                parametro.put("fecha", retornarString(fc.getFecha()));
                parametro.put("usser",fc.getId_us().getNombre());
                parametro.put("cliente", (fc.getId_prov().getRazon_social()));
                parametro.put("ruc", fc.getId_prov().getRuc());
                parametro.put("total",txttotal.getText());
                JasperPrint fillReport = JasperFillManager.fillReport(report, parametro ,new JRBeanCollectionDataSource(fac));
                JasperViewer jviewer = new JasperViewer(fillReport,false);
                    jviewer.setTitle("Factura de Ventas");
                    jviewer.setVisible(true);
                } catch (JRException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte 1 ."+e);        
            } catch (HibernateException e) {
                JOptionPane.showMessageDialog(null, "Error cargando reporte."+e);
        }
        }
    
}
