/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.app.Servicios;

import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.Modelos.Cliente;
import net.Modelos.Recepcion;
import net.Modelos.Usuario;
import net.Modelos.datos_login;
import net.dao.ClienteDaoImpl;
import net.dao.LoginDaoImpl;
import net.dao.RecepcionDaoImpl;
import net.dao.UsuarioDaoImpl;
import net.util.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Searp
 */
public class RecepcionApp extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public RecepcionApp(java.awt.Frame parent, boolean modal) throws UnknownHostException {
        super(parent, modal);
        initComponents();
        arranque();
        setLocationRelativeTo(null);
    }

    Session st = HibernateUtil.getSessionFactory().openSession();
    private final LoginDaoImpl logdao= new LoginDaoImpl(st);
    private final RecepcionDaoImpl rdao = new RecepcionDaoImpl(st);
    private final UsuarioDaoImpl udao = new UsuarioDaoImpl(st);
    private final ClienteDaoImpl cdao = new ClienteDaoImpl(st);
    private DefaultTableModel modelclie, model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar_cliente = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaclie = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        filcliente = new javax.swing.JTextField();
        agregarclie = new javax.swing.JButton();
        cancelarclie = new javax.swing.JButton();
        Buscar_Recepcion = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaped = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        agregarped = new javax.swing.JButton();
        cancelarped = new javax.swing.JButton();
        fechaped = new javax.swing.JFormattedTextField();
        buscarped = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        botbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtobservaciones = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtrazonsocial = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        botbuscarcliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        anular = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        estado = new javax.swing.JLabel();

        Buscar_cliente.setResizable(false);
        Buscar_cliente.setSize(new java.awt.Dimension(650, 750));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Buscar Cliente");

        tablaclie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaclie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "RUC", "RAZON SOCIAL"
            }
        ));
        jScrollPane4.setViewportView(tablaclie);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        filcliente.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        filcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filclienteKeyTyped(evt);
            }
        });

        agregarclie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarclie.setText("Agregar");
        agregarclie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarclieMouseClicked(evt);
            }
        });

        cancelarclie.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarclie.setText("Cancelar");
        cancelarclie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarclieMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(agregarclie, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarclie, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelarclie, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarclie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filcliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_clienteLayout = new javax.swing.GroupLayout(Buscar_cliente.getContentPane());
        Buscar_cliente.getContentPane().setLayout(Buscar_clienteLayout);
        Buscar_clienteLayout.setHorizontalGroup(
            Buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_clienteLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        Buscar_clienteLayout.setVerticalGroup(
            Buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        Buscar_Recepcion.setSize(new java.awt.Dimension(650, 750));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Buscar Presupuesto");

        tablaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tablaped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO", "FECHA", "CLIENTE"
            }
        ));
        jScrollPane3.setViewportView(tablaped);

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        agregarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        agregarped.setText("Agregar");
        agregarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpedMouseClicked(evt);
            }
        });

        cancelarped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelarped.setText("Cancelar");
        cancelarped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarpedMouseClicked(evt);
            }
        });

        try {
            fechaped.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaped.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaped.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        buscarped.setText("Buscar Fecha");
        buscarped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fechaped, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buscarped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(agregarped, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarped, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarped, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(agregarped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaped, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout Buscar_RecepcionLayout = new javax.swing.GroupLayout(Buscar_Recepcion.getContentPane());
        Buscar_Recepcion.getContentPane().setLayout(Buscar_RecepcionLayout);
        Buscar_RecepcionLayout.setHorizontalGroup(
            Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        Buscar_RecepcionLayout.setVerticalGroup(
            Buscar_RecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscar_RecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Recepcion de Equipos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(212, 24, 378, 53);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel5.setText("Nro ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        txtnro.setEditable(false);
        txtnro.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtnro);
        txtnro.setBounds(62, 10, 90, 30);

        botbuscar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscar.setText("Buscar");
        botbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(botbuscar);
        botbuscar.setBounds(160, 10, 157, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(570, 10, 68, 30);

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtusuario);
        txtusuario.setBounds(660, 10, 153, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setText("Fecha");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(370, 10, 58, 30);

        txtfecha.setEditable(false);
        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfecha.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel2.add(txtfecha);
        txtfecha.setBounds(430, 10, 99, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 870, 60);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("Modelo");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(550, 20, 90, 30);

        txtmodelo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtmodelo);
        txtmodelo.setBounds(630, 20, 153, 30);

        txtcolor.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtcolor);
        txtcolor.setBounds(100, 70, 153, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel7.setText("Color");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 70, 90, 30);

        txttipo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txttipo);
        txttipo.setBounds(100, 20, 153, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel8.setText("Tipo dispositivo");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 20, 90, 30);

        txtmarca.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtmarca);
        txtmarca.setBounds(360, 20, 153, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel9.setText("Marca");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 20, 90, 30);

        txtobservaciones.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel3.add(txtobservaciones);
        txtobservaciones.setBounds(360, 70, 430, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setText("Observaciones");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(270, 70, 90, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 140, 870, 130);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel14.setText("Nro");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 20, 50, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel15.setText("RUC");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(150, 20, 50, 30);

        txtruc.setEditable(false);
        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        txtruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrucActionPerformed(evt);
            }
        });
        jPanel5.add(txtruc);
        txtruc.setBounds(200, 20, 130, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel16.setText("Razon Social");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(350, 20, 70, 30);

        txtrazonsocial.setEditable(false);
        txtrazonsocial.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(txtrazonsocial);
        txtrazonsocial.setBounds(420, 20, 310, 30);

        txtcliente.setEditable(false);
        txtcliente.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jPanel5.add(txtcliente);
        txtcliente.setBounds(80, 20, 50, 30);
        jPanel5.add(jLabel17);
        jLabel17.setBounds(1090, -120, 52, 900);

        botbuscarcliente.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        botbuscarcliente.setText("Buscar ");
        botbuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscarclienteActionPerformed(evt);
            }
        });
        jPanel5.add(botbuscarcliente);
        botbuscarcliente.setBounds(740, 20, 110, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 280, 870, 90);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        nuevo.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        nuevo.setText("NUEVO");
        nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMouseClicked(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        guardar.setText("GUARDAR");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        anular.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        anular.setText("ANULAR");
        anular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anularMouseClicked(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        salir.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        estado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(326, 326, 326)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 380, 870, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarActionPerformed
        buscarPresupuesto();
    }//GEN-LAST:event_botbuscarActionPerformed

    private void txtrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrucActionPerformed

    private void botbuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscarclienteActionPerformed
        buscarclientes();// TODO add your handling code here:
    }//GEN-LAST:event_botbuscarclienteActionPerformed

    private void nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMouseClicked
        nuevo();
    }//GEN-LAST:event_nuevoMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        try {
            guardar();
        } catch (UnknownHostException ex) {
            Logger.getLogger(RecepcionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarMouseClicked

    private void anularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anularMouseClicked
        anular();
    }//GEN-LAST:event_anularMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        try {
            arranque();
        } catch (UnknownHostException ex) {
            Logger.getLogger(RecepcionApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void filclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filclienteKeyTyped
        filcliente.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (filcliente.getText());//.toUpperCase();
                filcliente.setText(cadena);
                repaint();
                filtroCl();
            }
        });
        trsfiltro = new TableRowSorter(tablaclie.getModel());
        tablaclie.setRowSorter(trsfiltro);// TODO add your handling code here:
    }//GEN-LAST:event_filclienteKeyTyped

    private void agregarclieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarclieMouseClicked
        agregarCliente();// TODO add your handling code here:
    }//GEN-LAST:event_agregarclieMouseClicked

    private void cancelarclieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarclieMouseClicked
        Buscar_cliente.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarclieMouseClicked

    private void agregarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpedMouseClicked
        retornarPresupuesto();
    }//GEN-LAST:event_agregarpedMouseClicked

    private void cancelarpedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarpedMouseClicked
        Buscar_Recepcion.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cancelarpedMouseClicked

    private void buscarpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpedActionPerformed
        tablaPresupuesto();// TODO add your handling code here:
    }//GEN-LAST:event_buscarpedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepcionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepcionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepcionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepcionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecepcionApp dialog = null;
                try {
                    dialog = new RecepcionApp(new javax.swing.JFrame(), true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(RecepcionApp.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Buscar_Recepcion;
    private javax.swing.JDialog Buscar_cliente;
    private javax.swing.JButton agregarclie;
    private javax.swing.JButton agregarped;
    private javax.swing.JButton anular;
    private javax.swing.JButton botbuscar;
    private javax.swing.JButton botbuscarcliente;
    private javax.swing.JButton buscarped;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarclie;
    private javax.swing.JButton cancelarped;
    private javax.swing.JLabel estado;
    private javax.swing.JFormattedTextField fechaped;
    private javax.swing.JTextField filcliente;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaclie;
    private javax.swing.JTable tablaped;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtobservaciones;
    private javax.swing.JTextField txtrazonsocial;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    private Calendar f;
    private void arranque() throws UnknownHostException{
    //campos
    txtfecha.setEnabled(false);
    estado.setText(null);
    f = (Calendar.getInstance());
    txtfecha.setText(retornarString(f));
    txtnro.setEnabled(false);
    txtnro.setText(null);
    txtruc.setEnabled(false);
    txtruc.setText(null);
    txtcliente.setText(null);
    txtrazonsocial.setText(null);
    txttipo.setText(null);
    txttipo.setEnabled(false);
    txtmarca.setText(null);
    txtmarca.setEnabled(false);
    txtmodelo.setText(null);
    txtmodelo.setEnabled(false);
    txtcolor.setText(null);
    txtcolor.setEnabled(false);
    txtobservaciones.setText(null);
    txtobservaciones.setEnabled(false);
    
    //botones
    botbuscarcliente.setEnabled(false);
    botbuscar.setEnabled(true);
    nuevo.setEnabled(true);
    guardar.setEnabled(false);
    guardar.setText("Guardar");
    anular.setEnabled(false);
    
    retornarusuario();
    }
    
    private String retornarString(Calendar fecha){
        String retorno = null;
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        if(fecha!=null){
            retorno= sdf.format(fecha.getTime());
        }
        return retorno;
    }
    
    private String hostname;
    
    private void retornarusuario() throws UnknownHostException{
        List<datos_login> list = logdao.list();
        InetAddress localHost = InetAddress.getLocalHost();
        hostname = localHost.getHostName();
        if(list!=null){
            for(datos_login u: list){
                if(u.getEstado().equals(true) && hostname.equals(u.getMaquina())){
                    txtusuario.setText(u.getUsuario().getNombre());
                }
            }
        }   
    }
    
    private void nuevo(){
     //campos
     estado.setText(null);
     txttipo.setEnabled(true);
     txtmarca.setEnabled(true);
     txtmodelo.setEnabled(true);
     txtcolor.setEnabled(true);
     txtobservaciones.setEnabled(true);
    //botones
    nuevo.setEnabled(false);
    guardar.setEnabled(true);
    guardar.setText("Guardar");
    anular.setEnabled(false);
    botbuscar.setEnabled(false);
    botbuscarcliente.setEnabled(true);
    }
    
    private TableRowSorter trsfiltro;
    public void filtroCl() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(filcliente.getText(), 2));
    }
    
    private void tabclientes(){
        tablaclie.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaclie.getColumnModel().getColumn(1).setPreferredWidth(180);
        modelclie = (DefaultTableModel)tablaclie.getModel();
        modelclie.setNumRows(0);
        List<Cliente> list = cdao.list();
        for (Cliente l : list){
            modelclie.addRow(new Object[]{
                l.getId_clie(),l.getRuc(), l.getRazon_social()
            }); 
        } 
    }
        
    
    private void buscarclientes(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tabclientes();
        Buscar_cliente.setModal(true);
        Buscar_cliente.setLocation(x,y);
        Buscar_cliente.setLocationRelativeTo(null);
        Buscar_cliente.setVisible(true);
    }
    
    private void agregarCliente(){
        if(tablaclie.getRowCount() > 0){
            if(tablaclie.getSelectedRow() != -1){
                Cliente l = cdao.buscarPorId(Integer.parseInt(modelclie.getValueAt(tablaclie.getSelectedRow(), 0).toString()));
                txtcliente.setText(String.valueOf(l.getId_clie()));
                txtrazonsocial.setText(l.getRazon_social());
                txtruc.setText(l.getRuc());
                Buscar_cliente.dispose();
            }
        }
    }
    
     
    
     
    private void guardar() throws UnknownHostException{
        if(!txtruc.getText().isEmpty() && !txttipo.getText().isEmpty() && !txtcolor.getText().isEmpty() 
                && !txtmarca.getText().isEmpty() && !txtmodelo.getText().isEmpty()&& !txtcolor.getText().isEmpty()){
                    Usuario us = udao.buscarPorNom(txtusuario.getText());
                    Cliente cl = cdao.buscarPorId(Integer.parseInt(txtcliente.getText()));
                    Recepcion r = new Recepcion(f,txttipo.getText(),txtmarca.getText(),txtmodelo.getText(),txtcolor.getText(),txtobservaciones.getText(),us,cl,"ACTIVO");
                        rdao.guardar(r);
                        JOptionPane.showMessageDialog(null, "Registro guardado correctamente");
                        arranque();  
        }else{
            JOptionPane.showMessageDialog(null, "Campo vacio. Rellene correctamente");
        }
    }
    
    private void anular(){
        if(JOptionPane.showConfirmDialog(null, "Desea anular este registro,.", "Mensaje del Sistema.", JOptionPane.YES_OPTION) == 0){
            if(!txtnro.getText().isEmpty()){
                Recepcion r = rdao.buscarPorId(Integer.parseInt(txtnro.getText()));
                if(r.getEstado().equals("ACTIVO")){
                    r.setEstado("ANULADO");
                    anular.setEnabled(false);
                    rdao.actualizar(r);
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se puede anular este registro. Esta siendo utilizado en otra instancia");
                }
            }
        }
    }
    
    private void tablaPresupuesto(){
        tablaped.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaped.getColumnModel().getColumn(1).setPreferredWidth(180);
        tablaped.getColumnModel().getColumn(2).setPreferredWidth(180);
        model = (DefaultTableModel)tablaped.getModel();
        model.setNumRows(0);
        List<Recepcion> list = rdao.list();
        for (Recepcion l : list){
            if(fechaped.getText().equals("  /  /    ")){
               model.addRow(new Object[]{
                l.getId_rec(), retornarString(l.getFecha()),l.getCliente().getRazon_social()
            }); 
            }else{
               if(fechaped.getText().equals(retornarString(l.getFecha()))){
                   model.addRow(new Object[]{
                l.getId_rec(), retornarString(l.getFecha()),l.getCliente().getRazon_social()
            }); 
               }
            }
            
        }
    }
     
     private void buscarPresupuesto(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        tablaPresupuesto();
        Buscar_Recepcion.setModal(true);
        Buscar_Recepcion.setLocation(x,y);
        Buscar_Recepcion.setLocationRelativeTo(null);
        Buscar_Recepcion.setVisible(true);
    }
     
     private void retornarPresupuesto(){
        if(tablaped.getRowCount() > 0){
            if(tablaped.getSelectedRow() != -1){
        Recepcion r = rdao.buscarPorId(Integer.parseInt(model.getValueAt(tablaped.getSelectedRow(), 0).toString()));
        txtfecha.setText(retornarString(r.getFecha()));
        txtusuario.setText(String.valueOf(r.getUsuario().getNombre()));
        txtnro.setText(String.valueOf(r.getId_rec()));
        txtcliente.setText(String.valueOf(r.getCliente().getId_clie()));
        txtruc.setText(String.valueOf(r.getCliente().getRuc()));
        txtrazonsocial.setText(String.valueOf(r.getCliente().getRazon_social()));
        txttipo.setText(String.valueOf(r.getTipo()));
        txtmarca.setText(String.valueOf(r.getMarca()));
        txtmodelo.setText(r.getModelo());
        txtcolor.setText(r.getColor());
        txtobservaciones.setText(r.getObservaciones());
        
        Buscar_Recepcion.dispose();
        botbuscar.setEnabled(false);
        estado.setText(r.getEstado());
        
        if(r.getEstado().equals("ACTIVO")){
            anular.setEnabled(true);
        }else{
            anular.setEnabled(false);
        }
        }
        }
    }
    
}
